### ISSUE TITLE
XSLTforms demo broken

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1072]
Heading for release 3.0: the XSLTforms demo seems to be disfunctional

**Comment by jensopetersen** [comment]
I don't see this. With a clean build of develop-07e86ab from 2016-08-24 everything works fine Which problems do you see, @dizzzz ?

**Comment by dizzzz** [comment]
For me, none of the apps was Actually working.....
Maybe a local plugin?

**Comment by jensopetersen** [comment]
So when the apps do not work for you, what is the error message?

**Comment by dizzzz** [comment]
hmmm , actually more demo's work. I found one with the TineMCE support:

![image](https://cloud.githubusercontent.com/assets/1700062/18190541/eb6db1a6-70c3-11e6-812f-4ad711c3967c.png)

**Comment by jensopetersen** [comment]
It's been years since I have looked at this. Unless @AlainCouthures can help out, I think we have to comment out the "Input Width" and "TinyMCE" demos.

**Comment by timathom** [comment]
This issue was raised last year: see #838. The diagnosis at the time seemed to be that the problem was related to whitespace handling (see #670). Not sure whether this was in fact the case.

Note that the version of XSLTForms in the eXist demo app is now quite outdated. It would be great if users of eXist could take advantage of the new features and enhancements that @AlainCouthures has implemented over the last two years.

**Comment by joewiz** [comment]
Indeed. Does XSLTForms have a champion in the eXist community who could help test and get the XSLTForms demo to work with the 3.0 in the develop branch to ensure it's working for the 3.0 release? If not, perhaps it should be pulled from the built-in demo. Someone could always create their own demo .xar and host it or contribute it if they want to.

**Comment by jensopetersen** [comment]
There are two issues here, @timathom: the inability to run recent versions of XSLTForms and the failure of the "Input Width" and "TinyMCE" demos to run with XSLTForms Rev. 594 and eXist 3.0. I made the XSLTForms Demo app, but as I wrote, I have been away from this for a long time (and don't do much with eXist-db anyway), so it would be nice if someone could take over or @AlainCouthures could help out. I don't see why the whole demo should be removed, if that is what you suggest, @joewiz.

**Comment by timathom** [comment]
@dizzzz @AlainCouthures I just tested this in eXist 3.0 with the latest version of XSLTForms (rev. 639), and all demos appear to be working as expected! The TinyMCE demo also works now, but I had to upload its form and dependencies from earlier versions, since the form seems to have been removed from eXist 3.0.

**Comment by dizzzz** [comment]
Cool!

**Comment by shabanovd** [comment]
can it be closed?

**Comment by timathom** [comment]
Yes, and also #838. However, it would be good if the TinyMCE demo were restored (right now, there is a broken link to it on the eXist XSLTForms demo page).

**Comment by shabanovd** [comment]
[here](http://exist-db.org/exist/apps/XSLTForms-Demo/index.html)?

**Comment by timathom** [comment]
Yes. In eXist 3.0, there is just a link there, but the tinymce.xml file is missing from the XSLTForms demo directory.
