### ISSUE TITLE
Nightly builds: eXist .exe installer does not work

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1112]
When trying to install the software with [eXist-db-setup-3.0.RC2-develop-07e86ab.exe](http://static.adamretter.org.uk/exist-nightly/eXist-db-setup-3.0.RC2-develop-07e86ab.exe) I get the following box:

![image](https://cloud.githubusercontent.com/assets/1700062/18279064/940b9df8-7454-11e6-8886-8e3d386d89c7.png)

 I tried a few different versions of .exe files; I tried a few Windows7/64bit/Java8 PCs around, all have same behavior.

Any idea where I can find a log/debug file of the installer?

**Comment by adamretter** [comment]
@dizzzz You might be able to find some further information from the *Event Viewer* in Windows. 

The actual `.exe` is created by  Launch4j, I have just upgraded from `3.5` to `3.9` on the build server in the hope that a newer version might solve your problem, I just created the build http://static.adamretter.org.uk/exist-nightly/eXist-db-setup-3.0.RC2-develop-503a734.exe if you would like to test that?

**Comment by dizzzz** [comment]
Thnx, I'll check tomorrow...

**Comment by dizzzz** [comment]
It looks like a local security agent blocks an action, blocking running the installer....

This means I cannot verify the .exe installer, anyone else maybe?

**Comment by adamretter** [comment]
I can confirm I have the same issue on a cleanish Windows 10 VM.

If you run:

```
eXist-db-setup-3.0.RC2-develop-503a734.exe --l4j-debug-all
```

The it will generate a `launch4j.log`. For me in there it claims that it is actually executing:

```
Launcher:	C:\Program Files\Java\jre1.8.0_101\bin\javaw.exe
Launcher args:	-jar "C:\Users\aretter\Downloads\eXist-db-setup-3.0.RC2-develop-503a734.exe"
```

If I manually execute the following from `cmd.exe`:
```
"C:\Program Files\Java\jre1.8.0_101\bin\javaw.exe" -jar "C:\Users\aretter\Downloads\eXist-db-setup-3.0.RC2-develop-503a734.exe"
```

Then the installer starts up, and I have to approve a security warning that I want `javaw` to be able to make changes to my computer, after that the installer runs fine.

So, I guess... when I launch the `.exe` directly, the error is caused because it cannot bring up the security warning that we need to agree to.

I suspect a bug in launch4j here, maybe worth contacting them about this if you need a Windows installer?

**Comment by dizzzz** [comment]
I guess 'the project' actually needs it....  ; @wolfgangmm  any ideas and or experiences?

**Comment by dizzzz** [comment]
Since the JAR works, we can drop the .exe ; java is needed anyway :-)

suggestion: @adamretter please could you remove the .exe's from the nightly builds?

**Comment by adamretter** [comment]
The launch4j .exe builds were dropped from eXist 3.0 onwards.
