### ISSUE TITLE
ft:query-field stops working when using declare variable

### ISSUE THREAD

**Issue by thvitt** [eXist-db/exist#1114]
I have indexed a bunch of TEI files into a Lucene field using a collection.xconf like:

``` xml
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index xmlns:tei="http://www.tei-c.org/ns/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <fulltext default="none" attributes="false"/>
        <lucene>
            <text field="text" qname="tei:l"/>
            <text field="text" qname="tei:p"/>
            <text field="text" qname="tei:head"/>
            <text field="text" qname="tei:stage"/>
        </lucene>
    </index>
</collection>
```

Now, if I run the following XQuery, I get a few results as expected:

``` xquery
xquery version "3.0";

<result>{ft:query-field('text', 'wiesenheu')}</result>
```

However, if I introduce a variable declaration such that the query is changed to the following, ft:query-field does no longer yields results — I only get the empty `<result/>` element:

``` xquery
xquery version "3.0";
declare variable $foo := 'bar';

<result>{ft:query-field('text', 'wiesenheu')}</result>
```

Tested using eXist 3.0 RC1, but I am quite sure the same problem already exists in eXist 2.2.

**Comment by joewiz** [comment]
The phenomenon of disappearing values amidst two let clauses seems related to #1106.

**Comment by joewiz** [comment]
Or rather disappearing values after a variable is bound. @shabanovd @jensopetersen, do you think these are related?

**Comment by thvitt** [comment]
Some additional observations, no idea if these are helpful:

(1) I've also observed the same problem with 
```xquery
xquery version "3.0";
declare namespace tei = 'http://www.tei-c.org/ns/1.0';
declare variable $foo := 'bar';

ft:query(//tei:l, 'wiesenheu')
```
while both that query without the variable declaration and the following form work:
```xquery
xquery version "3.0";
declare namespace tei = 'http://www.tei-c.org/ns/1.0';
declare variable $foo := 'bar';

//tei:l[ft:query(., 'wiesenheu')]
```

(2) Problem also occurs when nested in a function, i.e.:
```xquery
xquery version "3.0";
declare namespace tei = 'http://www.tei-c.org/ns/1.0';
declare variable $foo := 'bar';

declare function local:query($q as xs:string) as element() {
    <result>{ft:query-field('text', 'wiesenheu')}</result>
};

<doc>{
        local:query('wiesenheu')
}</doc>
```
returns
```xml
<doc>
<result/>
</doc>
```
as long as the variable declaration is present.

([Originally encountered this in an app using the templating framework](http://stackoverflow.com/q/39389508/1719996))

**Comment by olvidalo** [comment]
`range:index-keys `is affected by this as well. I've tried to look into it and found the following...

- in both function implementations, the `eval` function's contextSequence argument is `null` when there is no preceding variable declaration.
- it is an empty sequence when there *is* a preceding variable declaration somewhere in the query.

In both functions it is checked whether contextSequence is null and if it is, `context.getStaticallyKnownDocuments()` is used as the document set for the query, or else the documents from the context sequence. As a variable declaration somehow leads to an empty sequence being passed to the functions instead of null, the functions return zero results in that case.

I couldn't figure out how the empty sequence ends up there, but I suspect that this might be happening somewhere in the PathExpr.java `eval` function where currentContext is first set to the empty sequence and then passed all the way to the affected xquery functions.

But this is where I lost any grasp on what is actually happening in the code so I'll leave it to the devs to investigate further. I'd very much appreciate this being fixed as this is preventing me from some major performance improvements to my app :)

Relevant code:
* https://github.com/eXist-db/exist/blob/0b7207378512fcbca4f0acb64c648f8d93559a88/extensions/indexes/lucene/src/org/exist/xquery/modules/lucene/QueryField.java#L130
* https://github.com/eXist-db/exist/blob/0b7207378512fcbca4f0acb64c648f8d93559a88/extensions/indexes/range/src/org/exist/xquery/modules/range/IndexKeys.java#L50
* https://github.com/eXist-db/exist/blob/0b7207378512fcbca4f0acb64c648f8d93559a88/src/org/exist/xquery/PathExpr.java#L207-L295
