### ISSUE TITLE
Dashboard login popup not displaying on the most recent Chrome version

### ISSUE THREAD

**Issue by mrangnekar** [eXist-db/exist#1150]
http://exist-db.org/exist/apps/dashboard/index.html login popup not displaying on Chrome 54.0
dijitpopup not working.

**Comment by dizzzz** [comment]
please can you share a screenshot?

**Comment by joewiz** [comment]
I'm also unable to reproduce, using same OS & Chrome version as @dizzzz. 

@mrangnekar I assume you mean the URL you provided and **not** your own eXist installation? In this case, no need to report your eXist-db version.

**Comment by mrangnekar** [comment]
![existdb](https://cloud.githubusercontent.com/assets/22903954/19576918/957cbfb6-96da-11e6-90c7-53d78f368386.png)
It's the url  http://exist-db.org/exist/apps/dashboard/index.html
Behaves same way on Mac and Windows with Chrome recent version

**Comment by dizzzz** [comment]
I actually tested my local version :)

The demo server need to be updated, I think it is RC1 or older?  @JoernT @ljo

**Comment by joewiz** [comment]
Please right-click on the page and select "Inspect" to bring up Chrome's developer window. Select the Console pane and shift-reload the page. Are any errors reported? If not, select the Network pane and shift-reload the page again. Do any of the requests have a status other than 200 or 304?

**Comment by mrangnekar** [comment]
Also my local version doesn't work-Dijitpopup doesn't get displayed

**Comment by joewiz** [comment]
@dizzzz So you are able to reproduce? (I am still unable to, in Chrome or Safari.)

@mrangnekar Okay, then you need to report your eXist-db version.

**Comment by mrangnekar** [comment]
existdb project version 2.2

**Comment by dizzzz** [comment]
Can't reproduce

Do you have any content / JavaScript blockers running?

**Comment by sgmlguru** [comment]
I have this problem on Chrome 54.0.2840.71 in Linux running eXist 2.2. Interestingly, if I click on Collections instead, the Login popup appears and I can log in. 

Oh, and I have no content or JavaScript blockers running.

**Comment by mrangnekar** [comment]
Please see attached- This is on Chrome 54.0

**Comment by dizzzz** [comment]
also  55.0.2883.21 beta (64-bit) works like a charm. interesting....

**Comment by sgmlguru** [comment]
As I said, Chrome 54.0.2840.71, 64-bit, running on Ubuntu Linux and the Cinnamon desktop. I got Chrome directly from Google, so not the upstream Chromium one. Also, the eXist DB install is completely fresh.

I can reproduce this behaviour on Windows and macOS. The difference between my setup and everybody else's, of course, is that I am syncing my Chrome setting on all of my computers, so I should probably test what happens when running a non-synced Chrome.

**Comment by sgmlguru** [comment]
So I just tried the following on my Linux install:

Removed the addon (Adblock Plus, that was already disabled on localhost where I access eXist). No login popup.

Disconnected the browser from my Google account and deleted cache, cookies, etc. No login popup.

Completely removed Chrome, including everything in ~/.config/google-chrome. Reinstalled version 54.0.2840.71, 64-bit, (Google's .deb package) but without any settings or changes whatsoever, and immediately went to localhost. No login popup.

Also tested installing Chromium, v 53.0.2785.143, 64-bit, from Ubuntu's .deb sources. Vanilla, nothing extra. No login popup.

Then I remembered that I do have one laptop with Chrome and a local eXist instance, never synced with my Google account. This is a client laptop running Win7. When I checked the Chrome version, it was 53 something but started to automatically upload a later one, so I quickly checked eXist. The popup login worked.

After the update, it was on latest 54 something and the login popup still worked.

And finally, I tested using my wife's laptop (Win 10, 64-bit, Chrome 54 something) and opened a remote eXist instance I have running on a VPS. No login popup.

My conclusions? Not that many, but it's fairly obvious that the exact version of Chrome doesn't matter. I'm starting to wonder if there is some weird external dependency of some kind. This is driving me nuts.

**Comment by dizzzz** [comment]
thank you for your extensive investigation and .... patience. Maybe @wolfgangmm @JoernT or @windauer have a similar experience?

**Comment by joewiz** [comment]
To the people who are seeing the problem: following the suggestions at https://github.com/eXist-db/exist/issues/1150#issuecomment-255222510 and reporting the error info requested may yield helpful troubleshooting information - especially JavaScript errors reported via the Console pane.

**Comment by sgmlguru** [comment]
Sorry for not getting back with more feedback earlier.

Testing this on eXist 3.0 (that I finally got running after resetting my browsers). Chrome v  54.0.2840.71 (64-bit) on Ubuntu Linux and the Cinnamon desktop won't show the login popup. Firefox v 51.0.1 (64-bit) has the same issue. Neither has any plugins or add-ons enabled.

I've followed Joe's debug suggestions in Chrome but no errors are reported. There's just no login popup unless I click on the Collection Browser when logged out.

**Comment by mathias-goebel** [comment]
as it affected my instances / browser combination (Version 59.0.3071.86 (Official Build) (64-bit)) as well, i can recommend using the Monex app to login - it will create a persistent session/cookie and the dashboard will work as expected. it is just a workaround, but ok.

lets have a look on the browsers console:

1. loading dashboard app:
   - nothing besides a console.log from `dashboard-1.7.js:373 Login: Not logged in`
2. when clicking on "Not logged in" - i wnat the popup:
   - nothing. the button will be highlighted, but nothing else happens.
3. when clicking on one of the apps loading within the dashboard (e.g. collection browser)
   - triggers the popup (YEAH!)
   - login works
   - everything is fine within this app (collection browser, backup, scheduler tested so far)
4. since we have a login (see 3.) we want to manage some packages
   - but why i am asked to login again? ok, at least we see the opoup.
   - login doesnt work, JS XHR fires full blast
```log
dojo.js:182 Error: Unable to load plugins/packageManager/packageManager.html status:401
dojo.js:54 Error: Unable to load plugins/packageManager/packageManager.html status:401
dojo.js:54 Error: Unable to load plugins/packageManager/packageManager.html status:401
dojo.js:54 Error: Unable to load plugins/packageManager/packageManager.html status:401
```

**Comment by gmella** [comment]
Just a small feedback because I noticed that login in the dashboard as admin with "Remember me" checked changed a lot the behaviour of the package manager after that.
