### ISSUE TITLE
Log in problems with eXist

### ISSUE THREAD

**Issue by felixderglueckliche** [eXist-db/exist#1253]
Hello world of eXist,

I am developing a web application on eXist. I setted up a new server for that so I don't have to use the Jetty server. Since 2 weeks I cannot really log in with my log in dates. When I try that for example on the dashboard it works but when I refresh the page or interact with the system (e.g. when I open eXide or the Package Manager) I am no longer logged in. Seems like it is not remembered then. This is curious because at the beginning it worked well. Don't really know what to do because I don't even know whether this problem is a server or an eXist problem.
I am thankful for every hint.

Best regards,
Felix

**Comment by joewiz** [comment]
@felixderglueckliche Sorry for the inconvenience, but could you please post your question to the exist-open mailing list: https://lists.sourceforge.net/lists/listinfo/exist-open. The issue tracker is meant for reporting confirmed bugs rather than general support & questions. A much larger portion of the eXist community reads exist-open, meaning you'll get better results there. 

Also, please include your eXist version in your email - and please close this issue when you've moved the post to exist-open.

**Comment by JoernT** [comment]
is this still a valid ticket or outdated?

**Comment by dizzzz** [comment]
"I setted up a new server for that so I don't have to use the Jetty server" means.... tomcat?
