### ISSUE TITLE
config:app-info() does not list dependencies

### ISSUE THREAD

**Issue by tgraham-antenna** [eXist-db/exist#1311]
### What is the problem

The default `index.html` includes `<div data-template="config:app-info"/>`.  That is supposed to generate "a table showing all properties defined in the application descriptors."  However, `<dependency>` (and `<permissions>`) has attributes, and they don't show.

### What did you expect

The dependency information.

This can be fixed by outputting all attributes (except `password` attributes):

````
Index: modules/config.xqm
===================================================================
--- modules/config.xqm	(revision 27934)
+++ modules/config.xqm	(working copy)
@@ -89,7 +89,7 @@
                 return
                     <tr>
                         <td>{node-name($attr)}:</td>
-                        <td>{$attr/string()}</td>
+                        <td>{$attr/string()}{string-join($attr/@* except $attr/@password, ' ')}</td>
                     </tr>
             }
             <tr>
````

### Context information
- eXist-db version + Git Revision hash : eXist-db 3.0 /  acd0c14

**Comment by joewiz** [comment]
@tgraham-antenna Let me ensure this issue is posted in the correct repository. Where are you seeing the file in question? 

The only similar `modules/config.xqm` file I'm aware of are in other apps' repositories:

- https://github.com/wolfgangmm/eXide/blob/develop/modules/config.xqm#L61-L83
- https://github.com/wolfgangmm/eXide/blob/develop/templates/bootstrap/modules/config.xqm#L74-L100
- https://github.com/wolfgangmm/eXide/blob/develop/templates/existdb/modules/config.xqm#L74-L100
- http://gitlab.exist-db.org/tei-publisher/tei-publisher-app/blob/master/modules/config.xqm#L271-297

**Comment by tgraham-antenna** [comment]
I did 'Application > New application' in eXide, and the `config.xqm` file was created/copied for me.  I don't know where it came from, but I expect that it's one of:

- https://github.com/wolfgangmm/eXide/blob/develop/templates/bootstrap/modules/config.xqm#L74-L100
- https://github.com/wolfgangmm/eXide/blob/develop/templates/existdb/modules/config.xqm#L74-L100

**Comment by joewiz** [comment]
Sounds right. Could I trouble you to move this issue to https://github.com/wolfgangmm/eXide/issues ? Thanks.

**Comment by tgraham-antenna** [comment]
Sorry about that.  From this distance, it all looks like eXist.  Now wolfgangmm/eXide#152.

**Comment by joewiz** [comment]
@tgraham-antenna No worries, that's completely understandable. Thanks for your willingness to migrate it.
