### ISSUE TITLE
Too many opened HttpSession

### ISSUE THREAD

**Issue by alebastrov** [eXist-db/exist#1421]
Each HttpClient request to an application creates  a new HtppSession, which will be never used after. We should have possibility to release a HttpSession after having request processed. for instance with adding some header to HttpClient and in XQueryServlet we have to invalidate session in case this header is provided. It will allow us to save some memory during backup/restore procedure, because each file needs a single separate request, which creates a session

**Comment by dizzzz** [comment]
Please can you fill in the template for issues?
I have no clue what you are referring to, we need more structured input.

Thnx

**Comment by alebastrov** [comment]
Just do:
- add SessionCountListener to your App
- try to restore some backup
- watch how many HttpSessions awere opened but not closed.

In fact restoring each xml document will create an HttpSession, which is never closed (only by timeout)
Moreover, restoring a collections creates HttpSessions as well.

Of course I tested it on existDB 2.2 on Windows 7 Java 1.8.0 x64

**Comment by dizzzz** [comment]
sorry this is from me far from sufficient to have a look at the issue; i really expect you to fill-in the template, and provide all we need that we can easily reproduce your issue in a few seconds. The description makes no sense to me and probably many of us.

we are all volunteers here, so help us to help you.

**Comment by adamretter** [comment]
@alebastrov Can you provide the absolute minimum app which allows us to reproduce your issue please?

**Comment by dizzzz** [comment]
As no response, i propose to close the issue;

**Comment by adamretter** [comment]
@dizzzz We should probably allow 30 days. I think we could set a policy generally whereby if we don't have a response within 30 days, we send one reminder, and if no response in 14 days then we close and label as "abandoned". How does that sound?

**Comment by alebastrov** [comment]
I wrote how to reproduce it in seconds. Unfortunately I do not know how to do it with tests

**Comment by adamretter** [comment]
@alebastrov One of the pieces of information you did not provide was how you restored the backup.

I can however confirm that your issue happens when using the XML:DB / XML-RPC interfaces from the Java Admin Client.
Basically the Java Admin Client (which uses XML:DB over XML-RPC) is session-less , so every HTTP connection it makes to the server causes the server to create a new session.

I think we have two options here:
1) Configure the eXist-db Server not to create sessions at all on the XML:DB / XML-RPC interface.
2) Configure the eXist-db Java Admin Client to reuse the session id returned by the server from the first request.

I guess the question is whether the XML-RPC protocol should be stateful or not. I will do some looking into this and thinking about it...

**Comment by adamretter** [comment]
@alebastrov Okay so I think I found an issue in Jetty which was causing this, I have sent them a PR here - https://github.com/eclipse/jetty.project/pull/1985

**Comment by dizzzz** [comment]
Nice work!

**Comment by adamretter** [comment]
@alebastrov @dizzzz So good news, the Jetty project merged by changes. I guess we just need to wait for the next release and then update to that to close this one.

**Comment by dizzzz** [comment]
Nice !
