### ISSUE TITLE
Changes in white space handling 3.0.0 - 3.2.0

### ISSUE THREAD

**Issue by wsalesky** [eXist-db/exist#1437]
Change in white space handling when accessing files with webdav. Added white space after ‘pretty printed’ elements, where there should only be a line break. 

eXistdb versions:  3.0, 3.1.0 and 3.1.1 and 3.2.0, fine before version 2.2

Behavior noticed when files are edited via webdav, notably in oXygen. To reproduce the problem, deploy this small sample repository: 

https://github.com/wsalesky/white-space

Open the templates/page.html via webdav, make any small edit and re-save. You will notice the SVG icon now has added spaces and no longer aligns correctly. The icon code is on line 47 and is automatically pretty printed even if I save all the span elements as a single line. 

Correct:
<img width="361" alt="screen shot 2017-05-09 at 10 47 41 pm" src="https://cloud.githubusercontent.com/assets/1168206/25881222/ba1c8a2c-3509-11e7-93ba-16421d4ae46b.png">

Incorrect, after editing file via oXygen:
<img width="503" alt="screen shot 2017-05-09 at 10 47 25 pm" src="https://cloud.githubusercontent.com/assets/1168206/25881234/c8a4bbc8-3509-11e7-9fd5-1f9572010209.png">

**Comment by dizzzz** [comment]
is the change also visible in the webdav interface, or only when rendering?

**Comment by dizzzz** [comment]
@ljo ?

**Comment by wsalesky** [comment]
I only see it when rendering, not in the webdav interface. I think it happens when the record is saved to the db via webdav. I tested this by opening the record in oxygen. Close without any changes, the white space is fine. Make a small change anywhere in the document and save and the white space issue appears.

**Comment by joewiz** [comment]
@wsalesky Could you try editing `extensions/webdav/webdav.properties` to change [line 4](https://github.com/eXist-db/exist/blob/develop/extensions/webdav/webdav.properties#L4) of this file to:

    indent=no

(Removing the `#` to uncomment the line, of course.)

Then restart eXist, open your test file, make your edits, and save via WebDAV. I believe the problem you were seeing will go away. If so, then we can confirm that what you're seeing is a result of the WebDAV interface's serialization policy—which unless specified in the `webdav.properties` file is inherited from conf.xml's `serializer/@indent=yes` setting. 

I've been gathering some notes on whitespace-related settings and options in eXist, which I've posted here: https://gist.github.com/joewiz/b53612a8b7744b8d1d24d2028770a79d. 

You may also be interested in PR I've submitted for eXide, which makes the app into a serialization sandbox: https://github.com/wolfgangmm/eXide/pull/168. (To use this `native-adaptive-serialization` branch of eXide you have to be using a current build of eXist's develop branch, and, until [a bug I reported](https://github.com/eXist-db/exist/issues/1455) is fixed, you have to manually edit eXide's expath-pkg.xml.tmpl file to make eXide's eXist dependency `3.2.9` instead of `3.3.0`. 

Using this branch of eXide, we can see what happens when we serialize your `template/index.html` file with `indent=no` vs. `indent=yes`:

**`indent=no`**

> ![screen_shot_2017-06-12_at_12_20_54_pm](https://user-images.githubusercontent.com/59118/27043945-d63da3a6-4f69-11e7-9afa-a86d242875d4.png)

**`indent=yes`**

> ![screen_shot_2017-06-12_at_12_21_10_pm](https://user-images.githubusercontent.com/59118/27043976-f8abd688-4f69-11e7-9952-8c098df82ac7.png)

I hope this sheds some light on the issue. While I'm still learning about all of the factors that contribute to whitespace handling (as described in the gist I linked to above), I think you'll probably be better served by setting your `webdav.properties` to `indent=no`, if not changing the default in `conf.xml` to `serializer/@indent=no`.

**Comment by wsalesky** [comment]
@joewiz Thank for the tips. Did this work for you? What version of eXist? 

I am currently running v3.2.0 (Build 20170509024024). I tried both, changing `webdav.properties`  to `indent=no` and also (separately) `conf.xml` to `serializer/@indent=no`. Neither of these changed the problematic behavior in webdav (using Oxygen).

**Comment by joewiz** [comment]
@wsalesky I'm using eXist 3.3.0-SNAPSHOT (rev 8a2ec0906, built 201706120904). I haven't yet actually experimented with the conf.xml or webdav.properties files, but I was hopeful they would have helped, given my experiments with `indent=no` serialization through queries run in eXide. Drat, I'm disappointed that altering these settings didn't help. Given this, I'm curious to know if you're using all stock settings in conf.xml or if you've altered any other indexer or serializer-related properties in that file?

**Comment by joewiz** [comment]
Also, can you confirm that you configured oXygen to use eXist's WebDAV interface and not its XML-RPC interface?

**Comment by wsalesky** [comment]
I am using out of the box conf.xml and webdav.properties. 

I access the files in the db using oXygen via: http://localhost:8080/exist/webdav/db/  

This does not happen when I edit files in oXygen and save them to my remote eXist instance via our webhooks (using xmldb:store())

**Comment by dizzzz** [comment]
I think the file `webdav.properties` must be stored on `$EXIST_HOME`

**Comment by wsalesky** [comment]
Saving `webdav.properties` with `indent=no` into `$EXIST_HOME` and restarting eXist does seem to have solved this white space issue. 

Thanks @dizzzz and @joewiz

**Comment by dizzzz** [comment]
SO, I'ld probably need to change the default serialisation parameters in the webdav interface. And the replication extension....

**Comment by dizzzz** [comment]
@wsalesky I have been working on some changes in the webdav code, but during testing I realised I can not reproduce. Reading your report, it is a mixture of webdav, xmldv:store() exide etc. I got lost.

Please could you describe how I could best, most easy reproduce the issue you saw? in small steps..

**Comment by wsalesky** [comment]
The problem is only with webdav. Using the sample repository: https://github.com/wsalesky/white-space

Step 1. Deploy the repository
Step 2. Go to http://localhost:8080/exist/apps/white-space/index.html
Step 3. Open templates/page.html via webdav (using oXygen)
Step 4.  Make any small change and save page.html
Step 3. Refresh  http://localhost:8080/exist/apps/white-space/index.html

You should see the logo no longer aligns correctly.

**Comment by dizzzz** [comment]
upon the 1st install I immediately see the following (no editing)
<img width="257" alt="white_spce_bug" src="https://user-images.githubusercontent.com/1700062/27449633-5b036ad6-5789-11e7-8f53-fdef75a4db36.png">

**Comment by wsalesky** [comment]
Can you check your local version of the page.html? 

https://github.com/wsalesky/white-space/blob/master/templates/page.html#L48

There should be no spaces between the spans: 
`<span class="path1"/><span class="path2"/><span class="path3"/><span class="path4"/>`

If there are spaces you get the HTML output in the above screen shot. So if there are no spaces in the local version and there are in the deployed version, then the problem may be larger then I had thought. 

I do not have issues with deploying the .xar, only with webdav, I also do not have any special configuration settings.

**Comment by dizzzz** [comment]
for sure it is *not* a webdav (only) bug; when opening in either eXide or Oxygen (via the XMLRPC route, jars can be installed in oxygen), I immediately see the four spans on different lines. So for sure if you hit the save button, the 'indented' form is stored in the database.

When I remove the newlines, store it, the icon looks OK again. So it is a generic question: why is eXist indenting  the XML?  Possible answers: (1) because configured this way in config.xml or (2) many of the classes used to retrieve XML documents have their own indenting settings switched on.

(checked with:  XMLRCP, webdav, REST)

With my upcoming webdav change the serialisation params follow the `config.xml` settings .....
