### ISSUE TITLE
Insufficient synchronisation in FileSyncThread

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1699]
There seems to a technical synchronisation issue in `FileSyncThread`.

I can see several ways to fix, but I am not sure what @wolfgangmm's intention was exactly with regards to how that class should be used.

Basically [this call to `sync`](https://github.com/eXist-db/exist/blob/develop/src/org/exist/storage/journal/FileSyncThread.java#L12), enables a write to the `syncTriggered` variable without sufficient synchronisation.

**Comment by wolfgangmm** [comment]
The class is exclusively used by `org.exist.storage.journal.Journal` to flush the transaction journal to disk. This happens e.g. during checkpoints and is important to ensure database consistency. Because flush to disk can be really expensive on some OS, it is triggered in a background thread.

As far as I can see, the only call to `sync` which is not synchronized happens during shutdown. All calls go through the main `JournalManager.shutdown` though, which is itself synchronized. I thus don't see how a concurrency issue should arise.
