### ISSUE TITLE
BetterForm doesn't update master .xml file

### ISSUE THREAD

**Issue by lguariento** [eXist-db/exist#1703]
Hello,

I am looking at the demo 'contacts' of BetterForm. When I hit the 'update table' button the table on the browser gets updated indeed. Nevertheless, the underlying contacts.xml file remains unchanged. I'd like to use BetterForms in order to be able to get an interface to the xml files and have a nice graphic interface for editing fields in xml files. Is this possible? 

Something like

`<xforms:submission id="save" method="put" action="myfile.xml"/>`

doesn't appear to work.

Thanks in advance for any help. I'm running eXist-db 3.6.1 on Centos 7.4.1708 and jdk1.8.0_152.

**Comment by lguariento** [comment]
Just to know: is this a bug, something you'll fix at a later point, or something I can fix myself and about which I'm missing someting? Thanks!

**Comment by JoernT** [comment]
Yes, the contacts demo doesn't save anything - it's a demo ;)

Of course you can save the data with an explicit submission. However you have to notice the following:

1. you should use `resource` attribute instead of `action` - that's deprecated. The URI you give in the `resource` attribute is always relative to the baseURI which in your case will be an http: or https: URI. So the submission `resource` resolves relative to that. 
1. further it depends what you intend to do: do you want to update or store some data in eXistdb, a file on the server or send to another service?

When you answer is store or update in eXistdb (as i assume) something like the following might help to get the idea:

```
 <xf:submission id="s-update"
                              resource="modules/updateRecord.xql?id={bf:instanceOfModel('m-main','i-control-center')/uuid}&amp;set=descriptionSet&amp;workdir={encode-for-uri(bf:instanceOfModel('m-main','i-control-center')/workdir)}"
                              method="post"
                              replace="none">
               </xf:submission>
```

This is real world example sending the data of an instance via post to modules/updateRecord.xql. This XQuery will then do the actual storing in eXistdb. 

In your XQuery you then simply access the posted information e.g.

//read a param
let $newData := request:get-data()

//read the data
let $newData := request:get-data()

(please note that get-data will return a document - you'll likely want the payload and should use request:get-data()/*[1] to get the root-node)

hth,

Joern

**Comment by JoernT** [comment]
This is not an issue of the demo form - it's not saving by intend (not cluttering the server with bogus data)

**Comment by lguariento** [comment]
I'll look into it, thanks. I think that information regarding how to do a simple (though very common) thing such as having an input area and a 'save' button for saving the data into an xml file is very scant and outdated on the web. It would be good to have a section, on eXist-db's documentation (http://exist-db.org/exist/apps/doc/xforms.xml) or on Betterform demo pages, explaining why the demo doesn't save and how to enable that functionality.

Even the commented code in the xq file would be of great help. What do you think?

**Comment by JoernT** [comment]
@lguariento you find much more docs at betterform.wordpress.com
