### ISSUE TITLE
eXist-db on Jupyter Notebooks

### ISSUE THREAD

**Issue by ooduor** [eXist-db/exist#1748]
Jupyter notebooks are a handy way to write live code with markdown documentation that is easy to share and demonstrate steps. See [samples here](https://try.jupyter.org/).

I liken eXide IDE to Jupyter notebooks bar the ability to share live code and results. Having worked with both, I would like to suggest the addition of this feature. Basically, you would run raw XQuery commands just like you do on eXide, possibly even have XQuery declarations and get results on the same notebook.

### What is the feature
> An eXist-db integration to run XQuery on Jupyter Notebooks is similar fashion to eXide IDE and you can manipulate documents on the same directory as your Notebook and also print results like in eXide.

### What do I expect
> Import a library e.g. `%eXistdb notebook` make a connection to an eXist-db server and write raw XQuery code for execution. Raw XQuery here just means executing XQuery as in FLOWR and not wrapped as functions in other language implementations.

### Context information
Please always add the following information
- eXist-db
- Jupyter Notebooks

**Comment by duncdrum** [comment]
Similar suggestions and requests have come up in the past. I think the [exist-open](https://lists.sourceforge.net/lists/listinfo/exist-open) mailing list will be the better way to gather feedback on the idea. Or even better join a [community call]( https://existdb.hipchat.com/invite/300223/6ea0341b23fa1cf8390a23592b4b2c39) where its easier to have a discussion. 
Just out of curiosity have you tried including xquery execution in a Jupyter notebook via [eulexistdb](https://github.com/emory-libraries/eulexistdb)? Maybe [Xquery Fiddle](http://xqueryfiddle.liberty-development.net) could help in the interm

**Comment by ooduor** [comment]
Thank you @duncdrum. Good to know that this has been raised before elsewhere. I didn't see it on a quick search of the issues. I haven't heard of eulexistdb nor XQuery fiddle, I'm taking a look. Thanks

**Comment by joewiz** [comment]
@ooduor I think eXist integration for Jupyter would be great. If you're interested in implementing such a thing, you might consult @jonathanrobie's work on a similar integration for BaseX. See his article introducing it at http://jonathanrobie.biblicalhumanities.org/blog/2017/12/08/jupyter-tutorial/. He notes in the README for the companion git repository at https://github.com/biblicalhumanities/greek-new-testament that the XQuery code should be compatible with eXist.

**Comment by jonathanrobie** [comment]
Yes, the XQuery code should be compatible, the Python glue probably isn't.
You can find my implementation here:

https://github.com/biblicalhumanities/greek-new-testament/tree/master/labnotes/greeksyntax

But my module is designed specifically for Greek syntax and related
resources.  If you want a general-purpose integration for Jupyter then you
probably want to think about how results are displayed, since XML results
can be voluminous, and you probably want to think about how you store
results between individual calls, e.g. are you using Python or R support
for XML or creating some kind of persistent XQuery variable that goes
beyond XQuery per se, or ....

If all you can do is issue a raw XQuery and see the result, that's pretty
easy, but then I wonder if it's really that much better than just using the
IDE.  The real benefits of Jupyter probably require more thought.  To me,
at least, the ability to store results in variables is pretty important for
the Python and R support in Jupyter.

**Comment by joewiz** [comment]
Thanks for chiming in, @jonathanrobie. Very cool.

@ooduor Are your questions answered? I will close this now, as the development of this feature does not rely on any new functionality being added to the eXist core. Please feel free to share your work on this with the community via the exist-open mailing list.
