### ISSUE TITLE
Incorrect permission on parent collection when installing XAR

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1820]
### What is the problem
A XAR file can set default username/group name as owner of the collection that is created when the XAR is extracted and installed (e.g. /db/apps/foo). The problem is that the same ownership is applied to /db/apps

### What did you expect
Only /db/apps/foo should get then new ownership

### Describe how to reproduce or add a test
- in eXide create XAR file that introduces new username/password (maybe the Monex app can be used)
- install XAR via package manager
- check /db/apps ownership

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 : 4.1-snaphot
- Java version (e.g. Java8u121) - java8u161
- Operating system (Windows 7, Linux, MacOs) - macOS
- 32 or 64 bit - 64 bit
- Any custom changes in e.g. conf.xml - none

**Comment by wolfgangmm** [comment]
Can you reproduce this outside eXide? I see the changed owner when creating an app first time in eXide, but if I download it and install it via the dashboard, `/db/apps` ownership is not modified. The same applies to any other xar I tried. If this is the case, it appears to be an eXide issue rather than a general eXist problem.

**Comment by wolfgangmm** [comment]
I confirm the issue is in eXide and opened a PR.

Please reopen this issue if I'm wrong and you can still reproduce the unwanted behavior.
