### ISSUE TITLE
restore process hangs at restoring empty file

### ISSUE THREAD

**Issue by babslgam** [eXist-db/exist#1996]
### What is the problem
exist hangs during restore process if the file to restore is empty.

### What did you expect
that the file is restored (or skipped with a warning) and restoring process continues

### how to reproduce

install exist 4.2.1
create backup
restore backup via admin client
stuck at restoring /db/apps/shared-resources/resources/scripts/ace/mode-text.js (btw the file is not empty in the latest ace package)

### Context information
Please always add the following information
- eXist-db version: eXist-db 4.2.1
- Java version: 1.8.0_171
- Operating system: Windows 10
- 32 or 64 bit: 64 bit
- installed via JAR installer
- no custom changes to conf.xml

**Comment by adamretter** [comment]
I believe this is fixed. It should be in the next release. You could check
a nightly build...

On 5 Jul 2018 19:51, "babslgam" <notifications@github.com> wrote:

What is the problem

exist hangs during restore process if the file to restore is empty.
What did you expect

that the file is restored (or skipped with a warning) and restoring process
continues
how to reproduce

install exist 4.2.1
create backup
restore backup via admin client
stuck at restoring
/db/apps/shared-resources/resources/scripts/ace/mode-text.js (btw the file
is not empty in the latest ace package)
Context information

Please always add the following information

   - eXist-db version: eXist-db 4.2.1
   - Java version: 1.8.0_171
   - Operating system: Windows 10
   - 32 or 64 bit: 64 bit
   - installed via JAR installer
   - no custom changes to conf.xml

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eXist-db/exist/issues/1996>, or mute the thread

**Comment by babslgam** [comment]
is it possible to fix this for the 4.2.1 stable release with a patch?

**Comment by adamretter** [comment]
@babslgam Commits needed are in this PR - https://github.com/eXist-db/exist/pull/1955 You could cherry-pick them when rebuilding from source if you wanted too.
