### ISSUE TITLE
Changes to global variable reset in modules causes regressions

### ISSUE THREAD

**Issue by caseydawsonjordan** [eXist-db/exist#2042]
This commit: https://github.com/eXist-db/exist/commit/7e6b2691012cfccb76fd772c0aacfa5d55eaa505#diff-1a7f6e1a39c50b3b42adcf60d6dfc6bd 

changed the behavior for how global variables are reset in eXist. The issue is that multiple instances of modules are instantiated as part of normal system operation. However some modules are still in use when others are reset, this causes the global variables to be nullified across all instances of the module prematurely causing queries that rely on these to fail.

It seems that in order to prevent this from happening globalVariables must either not be static or more logic must be implemented to ensure that reset is not called while modules are still referenced or in use.

**Comment by caseydawsonjordan** [comment]
More details:

Our module looks something like this: 

```
public class LocalizationModule extends AbstractInternalModule {


	public static final String NAMESPACE_URI = "http://jorsek.com/content-management/modules/localization";
	
	public static final String PREFIX = "jcm-localization";
	public final static String INCLUSION_DATE = "2011-05-19";
	public final static String RELEASED_IN_VERSION = "eXist-1.4.x";
	
	
	public final static QName LOCALIZATION_METADATA_FIELD_XQUERY_VAR = new QName("LOCALIZATION_METADATA_FIELD", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX);
	public final static QName LOCALIZATION_JOBS_METADATA_FIELD_XQUERY_VAR = new QName("LOCALIZATION_JOBS_METADATA_FIELD", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX);
	
	public static final FunctionDef[] functions = {
		new FunctionDef(FormatLocaleNameFunction.signatures[0], FormatLocaleNameFunction.class)
    };

	public LocalizationModule(Map<String, List<? extends Object>> parameters) throws XPathException {
		super(functions, parameters, false);

		declareVariable(new QName("d2x-xsl", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX), LocalizationManagement.getD2XXslPath());
		declareVariable(new QName("x2d-xsl", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX), LocalizationManagement.getX2DXslPath());
		declareVariable(new QName("xliff-version", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX), LocalizationManagement.XLIFF_VERSION);
		declareVariable(new QName("xliff-ns", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX), LocalizationManagement.XLIFF_NS);
		declareVariable(new QName("xliff-xsi-schemaLocation", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX), LocalizationManagement.XLIFF_XSI_SCHEMALOCATION);
		declareVariable(new QName("xliff-complete-metadata-key", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX), LocalizationManagement.XLIFF_COMPLETE_METADATA_KEY);

		declareVariable(new QName("locale-md-field", LocalizationModule.NAMESPACE_URI, LocalizationModule.PREFIX), LocalizationManagement.STORED_LOCALE_LANG_CODE);
	}

	public String getNamespaceURI() {
		return NAMESPACE_URI;
	}

	public String getDefaultPrefix() {
		return PREFIX;
	}

	public String getDescription() {
		return "A module for localiziing XML documents.";
	}

	public String getReleaseVersion() {
		return RELEASED_IN_VERSION;
	}

}
```

Then we have an xql that attempts to use one of these defined variables and produces the following exception:

Caused by: org.exist.xquery.XPathException: err:XPDY0002 variable '$jcm-localization:d2x-xsl' is not set. [at line 12, column 18, source: file:generate-job-xliff.xql]
	at org.exist.xquery.VariableReference.eval(VariableReference.java:90)
	at org.exist.xquery.DynamicCardinalityCheck.eval(DynamicCardinalityCheck.java:74)
	at org.exist.xquery.functions.fn.FunDoc.eval(FunDoc.java:94)
	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41)
	at org.exist.xquery.LetExpr.eval(LetExpr.java:99)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.PathExpr.eval(PathExpr.java:276)
	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
	at org.exist.xquery.XQuery.execute(XQuery.java:261)
	at org.exist.xquery.XQuery.execute(XQuery.java:185)

----------- Example XQL------------

```
xquery version "1.0";

declare namespace local =  "local";

declare namespace jcm-localization="http://jorsek.com/content-management/modules/localization";

declare option exist:serialize "indent=no";

let $xsl := doc($jcm-localization:d2x-xsl)

return
	()
```

**Comment by adamretter** [comment]
I think you are looking at the`HEAD` of the `develop` branch, is that correct?

So I have started by creating  a very simple test as the basis for further discussion and tests. I  am able to reproduce your problem quite simply: https://github.com/adamretter/exist/blob/hotfix/internal-module-variables/test/src/org/exist/xquery/InternalModuleTest.java#L55

To start with I wanted to reason a little about ownership and concurrency:

1. When you call `AbstractInternalModule#declareVariable` you are inserting a key/value pair into `AbstractInternalModule#mGlobals` which is declared like so:
    ```java
    protected final TreeMap<QName, Variable> mGlobalVariables = new TreeMap<QName, Variable>();
    ```
    We can see from that, that there is one dedicated instance of `mGlobalVariables` for each instance of your Module.

2. The `mGlobalVariables` is read from `XQueryContext#resolveVariable` calling `AbstractInternalModule#resolveVariable` which looks up the module, and then tries to see if the module has the named variable declaration.
    There is one dedicated instance of `XQueryContext` per executing XQuery. Although an `XQueryContext` object can be recycled after it is finished with and used in future for a new XQuery.

3. The `mGlobalVariables` is cleared after the query finishes executing by `XQueryContext.reset(keepGlobals=false)` calling `AbstractInternalModules.reset(context, keepGlobals=false)`.

That is all fine in itself. However, the problem seems to come about when the `XQueryContext` is re-used for a subsequent XQuery invocation. The XQueryContext, still has the module registered in it's `modules` from the first invocation, which means it will use the existing instance of the module and not create a new instance by calling `XQueryContext#initBuiltInModule`, which would then call your modules constructor and set the variables again.

There are several different scenarios I see for fixing this:

1. We rollback the `reset` change for module variables that @wolfgangmm implemented. Unfortunately, I think he did this to fix a memory leak he identified. So this would likely mean the memory leak returns.

2. Don't reuse modules between XQuery invocations, this would be the simplest and easiest fix. It will likely have a performance impact though!

3. Redesign module API. There are lots of options here:
  1. Don't declare variables are from the constructor. Instead we add an `init` method, to complement the `reset` method.
  2. We define what can and can't change between module invocations. Some modules are effectively side-effect free, so we could get a large performance win here by only having one instance of a module for the entire database.
  3. *Lots of other options here...*
