### ISSUE TITLE
HTML5 doctype is removed when saving, editing or serving static HTML5 files

### ISSUE THREAD

**Issue by metacontext** [eXist-db/exist#2056]
### What is the problem
When importing / saving static HTML5 files (e.g. via the collection browser or oXygen) the doctype gets removed. When editing those files in eXide the doctype is not present and also cannot be included manually (inserting and saving has no effect). Serving those files to the browser results in an XML-prologue being inserted instead. When exporting the files the former HTML5 doctype is also not present anymore.

Interesstingly, when generating and saving static HTML5 files via the serialize() function and xmldb:store() everything works as expected.

### What did you expect
eXist should not change imported static HTML5 files and always keep the HTML5 doctype

### Describe how to reproduce or add a test
Import any valid static HTML5 file in eXist with the collection browser and open it in eXide.

### Context information
- eXist-db version: all versions from 3.2.0 onwards
- Java 8 171 on Mac, Oracle java "1.8.0_181" on Debian
- Linux and Mac
- 64 bit
- JAR and DMG

**Comment by joewiz** [comment]
See the mailing list discussion of the doctype issue from 2009 at https://markmail.org/thread/27fxcjicang6yk3q, and the recent discussion of this issue peeling apart the relevant layers at https://github.com/eXist-db/eXide/issues/198.

**Comment by adamretter** [comment]
I would love to get to the bottom of the Doctype handling stuff and fix it once and for all; It seems from what I have read, that it hasn't been properly implemented since at least 2009, which is a bit bad really :-/

I want to fix the issues in eXist-db and it's API's and then App developers can fix anything they need themselves.

As I understand it, if you store a document into eXist-db, the Doctype declaration (or at least the `ExternalID` (public/private parts) of it) will be captured and stored. Most of the discussion in the mailing-list thread that @joewiz referenced (https://markmail.org/thread/27fxcjicang6yk3q) seemed to be around serialization.

I think we need to do a few things:

1. Store the entire Doctype declaration not just the ExternalID. As described by - https://www.w3.org/TR/xml/#dtd

2. Fix the Serializer (and possibly also the Indexer?).
    In @wolfgangmm's reply to thread of Oct 21st 2009, he states:
    > The serializer ignores the doctype declaration by default. Reason: we 
cannot be sure that the doctype declaration would be correct and 
complete. The original XML document may have declared an internal 
subset, which the indexer could not see and thus not store.

    It is not entirely clear to me what @wolfgangmm means by this? However, I would suggest, that if someone stores an XML document with a DTD Internal Subset, then we must ensure that the document must adhere to that subset at ingest time, and the time of any modifications made to it, and also at serialization time. I think we need to understand Wolfgang's comments on this.

3. Ensure that the (fixed) serialization is used correctly in each API. especially WebDav (as we have had complaints from Oxygen users in the past about Doctype declarations.

I am ready to do this work and make it specification compliant. Perhaps the next steps is that we just need some discussion between @joewiz, @wolfgangmm and myself, to define the scope?

**Comment by metacontext** [comment]
@adamretter @joewiz Thanks a lot for the helpful information and your efforts! A fix would be great since this issue comes up quite regularly as I also know from talks with my colleagues. As @dariok has said in the other thread from a users perspective it is surprising that eXist would change the contents of binary files during ingestion (making it necessary to (re)serialize the file). If you need testers for this feature please don't hesitate to ask. Thanks again and best regards!

**Comment by duncdrum** [comment]
see #2368 
@wolfgangmm @adamretter did your discussion come to some kind of conclusion?
@metacontext adding tests for the presence of the doctype declaration before and after storage would certainly help us here. However, i would like to ask you to focus on the exist-code part here, if there are problems with how eXide or the collection browser act, these should be discussed in separate tickets in their repos.
