### ISSUE TITLE
Docker build for 5.0.0RC3 does not work

### ISSUE THREAD

**Issue by zopyx** [eXist-db/exist#2122]
I tried to build the Docker image for the latest 5.0.0 RC release using

https://hub.docker.com/r/existdb/existdb/~/dockerfile/

and this fails:

Step 15/28 : COPY --from=builder /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8 /usr/lib/x86_64-linux-gnu/liblcms2.so.2
 ---> 52ac0864623d
Step 16/28 : COPY --from=builder /usr/lib/x86_64-linux-gnu/libpng16.so.16.28.0 /usr/lib/x86_64-linux-gnu/libpng16.so.16
 ---> 03d41aae47bc
Step 17/28 : COPY --from=builder /etc/fonts /etc/fonts
 ---> d60068e64cc0
Step 18/28 : COPY --from=builder /lib/x86_64-linux-gnu/libexpat.so.1 /lib/x86_64-linux-gnu/libexpat.so.1
 ---> 8f9b65004e6d
Step 19/28 : COPY --from=builder /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0 /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
 ---> 7884dad8b9ad
Step 20/28 : COPY --from=builder /usr/share/fontconfig /usr/share/fontconfig
 ---> 50e2f1af8b6e
Step 21/28 : COPY --from=builder /usr/share/fonts/truetype/dejavu /usr/share/fonts/truetype/dejavu
 ---> 3472725277a4
Step 22/28 : COPY ./src/log4j2.xml $EXIST_HOME/config
COPY failed: stat /var/lib/docker/tmp/docker-builder241324146/src/log4j2.xml: no such file or directory
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by duncdrum** [comment]
RC builds require manual building since we're automatically building full releases and bleeding edge (each commit in the main repo)
to build locally you need the git-ref of the RC release 
`docker build --build-arg BRANCH=eXist-5.0.0-RC3 .`

we have published a RC3 image so simply:
`docker pull existdb/existdb:5.0.0-RC3` will do the trick.
