### ISSUE TITLE
Disable Oracle Java10 build on travis

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#2227]
As it is now deprecated; should we focus on Java8/Java11 only?

![image](https://user-images.githubusercontent.com/1700062/47282237-b7542080-d5de-11e8-9c47-de5eb0a382ec.png)

**Comment by dizzzz** [comment]
ping

**Comment by adamretter** [comment]
What value does disabling it give us? I would assume there are users out there with Oracle's JDK10

**Comment by dizzzz** [comment]
Java9/10 are EOL, unsupported, cannot be downloaded anymore. PPL need to upgrade anytime soon anyway....

Travis does not provide Oracle Java10 to us anymore, so we have to disable it anyway.
I'd say... lets focus on Java8 and Java11 alone. will make the builds faster

**Comment by dizzzz** [comment]
it is biting https://github.com/eXist-db/exist/pull/2169#issuecomment-431779949

**Comment by duncdrum** [comment]
for consistency we should disable both oracle java9 and java10 builds on travis, but keeping their openjdk counterparts. As far as i am concerned this satisfies our due diligence towards users running EOL oracle java versions. 

Not that exist-db would run on java > 8 on macOS right now.

**Comment by dizzzz** [comment]
Fair enough, for now. As the version Iteration of Java is now accelerating, and new versions are EOLled faster than ever, we cannot afford (IMO) to follow the complete cycle. I'd recommend to have 'LTS' versions supported for a longer time: that is Java8 and Java11 for now.

And: I have no reason to upgrade java8 on my macs. it is still downloadable, the Java10 plugin has been forced removed by oracle last week. :-)

**Comment by duncdrum** [comment]
i think the open non-lts versions serve their purpose, as an early warning. I m on (open)java 10 since some of my stuff needs it, but exist-db is blocking me from going java11 across the board. 
I think this is a pattern that will continue to apply in the new world of java releases, so keeping non lts openjdk in the testsuite serves a good purpose.

Given that removing a java version also shortens our testsuite runs by 30min on average, removing stuff is very attractive. Overall,  I stick with my earlier post. Openjdk9 should be removed soonish (maybe after the next non hotfix release) but not today. We should continue to   test with whatever non lts major versions are the most recent. 

Sticking to oracles lts for testing is fine, imv.
