### ISSUE TITLE
programmatic installation with `repo:install-and-deploy` fails

### ISSUE THREAD

**Issue by mathias-goebel** [eXist-db/exist#2519]
### What is the problem
On eXist 4.6.0 the query 
`repo:install-and-deploy("openapi", "https://ci.de.dariah.eu/exist-repo/find.xql")` should be fine, but fails with
```xq
experr:EXPATH00 Failed to install dependency from https://ci.de.dariah.eu/exist-repo/find.xql?name=openapi&processor=4.6.0: https://ci.de.dariah.eu/exist-repo/find.xql?name=openapi&processor=4.6.0 [at line 3, column 1, source: xquery version "3.1";

repo:install-and-deploy("openapi", "https://ci.de.dariah.eu/exist-repo/find.xql")]
```

### What did you expect
As my processor is 4.6.0 i would expect the package to be deployed.

### reproduce
```xq
repo:install-and-deploy("openapi", "https://ci.de.dariah.eu/exist-repo/find.xql")
```

### Context information
- eXist-db 4.6.0
- java -version: openjdk version "1.8.0_201"
- Linux
- 64 bit
- eXist from bintray bz2

**Comment by joewiz** [comment]
Which version of the public-repo is installed on the server in question? Could you paste in the eXist `<dependency>` element from the `expath-pkg.xml` of the package in question?

**Comment by mathias-goebel** [comment]
```xml
<dependency processor="http://exist-db.org" semver-min="4.6.0"/>

<package xmlns="http://expath.org/ns/pkg" name="http://exist-db.org/apps/public-repo" abbrev="public-repo" version="0.6.0" spec="1.0"/>
```

**Comment by mathias-goebel** [comment]
i tried with 5.0.0-RC6, same result. Error message is
```
experr:EXPATH00 Failed to install dependency from 
https://ci.de.dariah.eu/exist-repo/find.xql?name=openapi&processor=5.0.0-RC6: 
https://ci.de.dariah.eu/exist-repo/find.xql?name=openapi&processor=5.0.0-RC6 
[at line 3, column 1, source: 
xquery version "3.1";
repo:install-and-deploy("openapi", "https://ci.de.dariah.eu/exist-repo/find.xql")]
```

**Comment by duncdrum** [comment]
I've seen similar problems with starting with RC6 in the node-exist repo [link](https://travis-ci.com/eXist-db/node-exist/jobs/180878891). Looks related to me, but could be coincidence

**Comment by joewiz** [comment]
@mathias-goebel Thanks for this info. I agree that your public-repo should be able provide the requested package given its eXist dependency declaration. I asked about your version of public repo because in the latest version of the public-repo app (currently v0.7.3) there are some fixes to dependency management, but the problems in earlier versions such as your version (v0.6.0) do not appear to be the cause of the error you're reporting. 

Instead, the problem has to do with both parameters you're supplying to the `repo:install-and-deploy()` function:

1. `$pkgName` should be the package's unique URI, i.e., the `/package/@name` in `expath-pkg.xml`, not the `@abbrev`
2. `$publicRepoURL` should lead to the actual location for the `find.xql` endpoint. The URL reported in both error messages returns a 404 error when requesting them directly in a browser (namely, https://ci.de.dariah.eu/exist-repo/find.xql?name=openapi&processor=4.6.0 and https://ci.de.dariah.eu/exist-repo/find.xql?name=openapi&processor=5.0.0-RC6). The correct endpoint for the find.xql module is `{app-name}/modules/find.xql`. 

Thus, if you change your code to the following, you should be all set:

```xquery
repo:install-and-deploy(
    "https://lab.sub.uni-goettingen.de/openapi4restxq", 
    "https://ci.de.dariah.eu/exist-repo/modules/find.xql"
)
```

Please confirm if this works for you.
