### ISSUE TITLE
Typo in an XQuery file for xqproc

### ISSUE THREAD

**Issue by lcahlander** [eXist-db/exist#2532]
### What is the problem
in `exist/extensions/xprocxq/main/src/xquery/std.xqm` line 104 has `: =` instead of `:=`
### What did you expect
Fix the typo

### Describe how to reproduce or add a test
N/A

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 5.0 / develop/1ae05530
- Java version 1.8.0_192
- Operating system MacOs
- 64 bit
- How is eXist-db installed? clone from GitHub
- Any custom changes   N/A

**Comment by joewiz** [comment]
Here's the link: https://github.com/eXist-db/exist/blob/develop/extensions/xprocxq/main/src/xquery/std.xqm#L104

That same file contains a static error:

> Cannot compile xquery: err:XQST0033 Cannot bind prefix `'err'` to `'http://www.w3.org/ns/xproc-error'` it is already bound to `'http://www.w3.org/2005/xqt-errors'`

While the spec says about `err`, "This namespace prefix is not predeclared," eXist does bind it, so this module couldn't pass static compilation...

Is anyone using xprocxq? The repo history says it's by @xquery, and hasn't been touched besides build maintenance in 8-10 years. See https://github.com/eXist-db/exist/tree/develop/extensions/xprocxq/main. As an implementation of XProc, I know that https://github.com/eXist-db/xquery-xproc-xmlcalabash-module is in use in production today and is probably quite a bit more up to date with the XProc standard, because XML Calabash itself is a reference implementation. 

I raise this to ask if we want to keep it in the code base? Perhaps it's a topic for a future community call?

**Comment by dizzzz** [comment]
it is old and abandoned code IMO. The concept is very nice though....

**Comment by dizzzz** [comment]
Xproc has become much more usable starting with v3 .....

**Comment by duncdrum** [comment]
Well i think replacing this code with the one Joe linked to sounds like a good idea. However, this would be a deprecation which we could add to 5.0.0 but it  needs to be marked as such. Also there is the need for documentation if we go the deprecation route. If we are not willing to deprecate this for 5.0.0 we should simple fix the bug.

**Comment by lcahlander** [comment]
If it is going to be deprecated, then it should be fixed until we actually remove it.  It should only be as an installable module as [https://github.com/eXist-db/xquery-xproc-xmlcalabash-module](url).  However, until it is removed, it should be working.  Until it is removed, each of the XQuery files should have the following added to the header:

```
(:~
 : @deprecated 
 : *2019-03-08*
 : To be removed in version 6 of eXist-db.  
 : Please use the `xquery-xproc-xmlcalabash-module` from the Package Manager.
 :)
```

or something like it.

**Comment by adamretter** [comment]
@joewiz I think we should simply remove `xprocxq`. As you pointed out it is now 8 - 10 years out of date!

**Comment by grantmacken** [comment]
Toss it overboard. And anything else that doen't move when you poke a stick at it
