### ISSUE TITLE
migrate docker tests

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist#2719]
### What is the problem
The old separate docker repo contains test files, to ensure that the images we publish are working as intended. We need to migrate these over, and integrate them into the new maven way of things.

The question is how to integrated them either as shell tests executed by a shell plugin, or by rewriting them as java tests. 

The second question is how these tests should integrate with other test to be run as integration tests via maven

### What did you expect
Published images to be tested.

### Context information
Please always add the following information
- eXist-db version 5.0.0-RC8-SNAPSHOT

**Comment by adamretter** [comment]
If you wanted to preserve the bats tests, then it is relatively easy.

1. Copy them over to `exist-docker/src/test/bats`

2. modify the `exist-docker/pom.xml` to execute the goal `docker:start` on `pre-integration-test` phase and `docker:docker-stop` on `post-integration-test` phase.

3. add the `maven-exec-plugin` on the `integration-test` phase to `exist-docker/pom.xml` to execute your bats tests.

The issue is that your tests will only run on Unix like platforms with bats installed. If we stick with that we would need to move them into a profile which is only activated on Unix.

...but is there perhaps a more platform agnostic way to write docker tests?
