### ISSUE TITLE
Backups broken in develop

### ISSUE THREAD

**Issue by wolfgangmm** [eXist-db/exist#2767]
### What is the problem
Restoring a backup created with current develop will result in all binary files missing. It doesn't matter if you restore into a remote or local instance. 

The `__contents__.xml` descriptors inside the backup are missing entries for all binary files.

Backup/restore was tested extensively not long ago, so this bug must have been introduced very recently.

### Describe how to reproduce or add a test
A backup is attached. On a fresh database, install a package which is not contained by default, e.g. the demo app. Create a backup via the dashboard and check the `__contents__.xml` files contained inside. They should be missing entries for all binary resources. Restoring the backup will thus miss all binary resources.

### Context information
Please always add the following information
- eXist-db 96993a5d3132f0469f13a46a5e6e0ccc99b837d4
- Java version 1.8.0_181
- Operating system (MacOs)

[full20190530-1459.zip](https://github.com/eXist-db/exist/files/3237243/full20190530-1459.zip)

**Comment by adamretter** [comment]
@wolfgangmm Okay so the backup process from the Java Admin Client works just fine. It seems to be just the backup process triggered from the Dashboard. I have no idea how the Dashboard works, I will try and figure it and let you know...

**Comment by adamretter** [comment]
@wolfgangmm After a bit of a search, I have found that the Dashboard uses the `ConsistencyCheckTask` which uses the `SystemExport` as opposed to the backup classes used by the Java Admin Client and elsewhere.

As far as I can see, this can't have ever worked in 5.x.x. The reason being that the `SystemExport` will attempt to work with transactions, but because it is triggered from `TransactionManager#commit` it is not possible to start a new transaction. I am not quite sure how we can fix this yet...

**Comment by adamretter** [comment]
I would also add that these transaction errors are logged, but it seems that files that are skipped by the backup are never reported back to the Dashboard. This seems like a bit of a failing on behalf of the Dashboard as it gives the user the idea that everything worked fine, when in fact there are serious issues they need to attend to.
