### ISSUE TITLE
Race condition when invoking org.exist.backup.ExportMain

### ISSUE THREAD

**Issue by reinhapa** [eXist-db/exist#2893]
### What is the problem
When invoking `org.exist.backup.ExportMain` for a data export. In some cases the export process locks itself and can only be hard terminated.

### Describe how to reproduce or add a test
In order to reproduce the issue reliably apply the following patch to `develop`
```diff
diff --git a/exist-core/src/main/java/org/exist/storage/BrokerPool.java b/exist-core/src/main/java/org/exist/storage/BrokerPool.java
index da668df843..ceab3fcc56 100644
--- a/exist-core/src/main/java/org/exist/storage/BrokerPool.java
+++ b/exist-core/src/main/java/org/exist/storage/BrokerPool.java
@@ -406,7 +406,7 @@ public class BrokerPool extends BrokerPools implements BrokerPoolConstants, Data
         this.maxBrokers = conf.getProperty(PROPERTY_MAX_CONNECTIONS, maxBrokers);
         LOG.info("database instance '" + instanceName + "' will have between " + nf.format(this.minBrokers) + " and " + nf.format(this.maxBrokers) + " brokers");
 
-        this.majorSyncPeriod = conf.getProperty(PROPERTY_SYNC_PERIOD, DEFAULT_SYNCH_PERIOD);
+        this.majorSyncPeriod = 200; //conf.getProperty(PROPERTY_SYNC_PERIOD, DEFAULT_SYNCH_PERIOD);
         LOG.info("database instance '" + instanceName + "' will be synchronized every " + nf.format(/*this.*/majorSyncPeriod) + " ms");
 
         // convert from bytes to megabytes: 1024 * 1024
@@ -536,7 +536,7 @@ public class BrokerPool extends BrokerPools implements BrokerPoolConstants, Data
         if(majorSyncPeriod > 0) {
             final SyncTask syncTask = new SyncTask();
             syncTask.configure(conf, null);
-            scheduler.createPeriodicJob(2500, new SystemTaskJobImpl(SyncTask.getJobName(), syncTask), 2500);
+            scheduler.createPeriodicJob(200, new SystemTaskJobImpl(SyncTask.getJobName(), syncTask), 200);
         }
 
         try {
```
After building a distribution and installing it perform the following command in the `lib` folder of the root installation directory:

```bash
java -cp $(find . -name '*.jar' -printf '%p:' | sed 's/:$//') -Xmx2g -Dexist.home=/<exist_root_instal_directory>/etc  org.exist.backup.ExportMain -x -z -d /tmp/exist_backup_test -v
```

**Comment by duncdrum** [comment]
Since this smells Locktably I ll let the Grandmaster weigh in. 
@adamretter thoughs?

**Comment by adamretter** [comment]
@reinhapa Okay, I can reproduce this.

1. The `sync` thread tells the transaction manager that it will begin a SYSTEM transaction
2. The `main` thread running the export locks the BTree
3. The `sync` thread tries to lock the BTree (which blocks on the `main` thread holding the lock)
4. The `main` thread tries to start a transaction (which blocks on the SYSTEM transaction)

Deadlock!

So we have to either:
1. Have the `NativeBroker#getCollectionsFailSafe(BTreeCallback)` require/take a transaction before locking the BTree.
2. Change `NativeBroker#getCollectionsFailSafe(BTreeCallback)` to be a System Task so that it has exclusive access to the database.

I am not sure whether `getCollectionsFailSafe` was designed with the intention of having exclusive access to the database or not? I think it was added by @wolfgangmm, perhaps he can comment on this?
