### ISSUE TITLE
Unable to restore backup on CLI

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#3119]
### What is the problem
It turns out not to be possible anymore to restore a back-up via CLI.

### What did you expect
Restore should work.

### Describe how to reproduce or add a test

the command

```
./bin/backup.sh -r ~/Desktop/full20190123-0300.zip -P MyPassword -R -ouri=xmldb:exist:///
```

works with exist-db v4.x (develop) but fails on v5.2.0-SNAPSHOT ; with an NPE or with the logging below:

```
Wrong password for user [admin] 
------------------------------------
Problems occurred found during restore:
ERROR: Wrong password for user [admin] 

Rebuilding application repository ...
URI: xmldb:exist:////db
Application repository rebuilt successfully.
shutting down database...
```

during v5.0 development era the restore has worked as I tested it before.

### Context information
Please always add the following information
- eXist-db version: v5.2.0-SNAPSHOT 
- Java version (e.g. Java8u121) - OpenJDK Runtime Environment (Zulu 8.42.0.23-CA-macosx) (build 1.8.0_232-b18)
- Operating system (Windows 7, Linux, MacOs) : macOS
- 32 or 64 bit : 64bit
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub) : clone
- Any custom changes in e.g. conf.xml : none

**Comment by adamretter** [comment]
AFAIK nothing has changed here between 5.0.0 and 5.1.0. Can you restore your backup in 5.0.0?

**Comment by dizzzz** [comment]
I will retry tonight...

**Comment by dizzzz** [comment]
@adamretter you are right, it does not work either for 5.0.0 ; in the time of  finalising v5.0 it has worked, as I was successful a few times.

I realize there is a special condition: the password ends with an "!" maybe that is a bad idea....

**Comment by dizzzz** [comment]
hmmmm the "!" in the password looks to be a crucial thingy. But only if the database is created by v4.0 of the database?! 

correlated to #3118

**Comment by craigberry** [comment]
I have definitely had command-line restores work in 5.0.0 for specific collections.  In doing a restore in 5.0.0 of a full backup created under 4.x, I never got it to complete because a 280GB journal file filled up the disk, but it got well past any problems with connecting and authenticating.  As it turns out, the admin password did in fact end with "!" but I never saw what you are describing so I doubt the problem can really be reduced to just that.

As I'm sure you know, you have to manually set the admin password of the target database to the same as whatever is in the security database of your full backup before restoring it.  Or at least I have always found it to be so.

**Comment by adamretter** [comment]
@dizzzz is this still an issue?

**Comment by dizzzz** [comment]
yes, I was able to reproduce it with the dataset I shared with you. It might be an issue with the "!" in the db password on unix cli.

**Comment by dizzzz** [comment]
no cannot reproduce it anymore
