### ISSUE TITLE
[BUG] With lucene index="no", querying ft:query(., ()) doesn't return all indexed nodes

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3205]
**Describe the bug**

When using the facets and fields feature in eXist 5, passing in an empty sequence in place of the query string should return, as stated in the documentation, "all articles in the collection." However, when `index="no"` is specified on the parent `<text>` element (so that content can be indexed via an explicit field), the technique of passing in the empty sequence to return "all articles" actually returns none.

My use case is: I want to be able to perform my full text queries using named fields and thus I want to set `index="no"` on the parent `<text>` element so the content isn't double-indexed. However, users can explore the collection via facets, too, so they won't always be providing keywords for full text search. Thus, we need to be able to allow the empty sequence as the query string and retrieve all results (whether facets are selected or not).

**Expected behavior**

I expected to be able to pass in an empty sequence in place of a query string when the `<text>` element has an `index="no"` attribute and return "all articles." 

The relevant documentation for these features can be found here:

(1) As stated in http://exist-db.org/exist/apps/doc/lucene#retrieve-fields:

> to view all articles in the collection you could pass in an empty sequence in place of the query string like this:
> 
> ```xquery
> //db:article[ft:query(., (), map { "fields": ("title", "author") })]
> ```

(2) And as stated in https://exist-db.org/exist/apps/doc/lucene#facet-conf:

> Or you can specify `index="no"` on the parent element and index its content with an explicit field.

**To Reproduce**

Below is an adaptation of https://github.com/eXist-db/exist/blob/develop/extensions/indexes/lucene/src/test/xquery/lucene/facets.xql#L418-L429, which queries an index defined as `<text match="/text/body/div" index="no">`. The query originally used `"english:*"` as the 2nd parameter of ft:query as a technique to return all English div elements.  However, this technique will trigger a "maxClauseCount is set to 1024" error given a dataset of any reasonable size, as I confirmed by pasting the text of [a long article](https://www.nytimes.com/interactive/2020/01/15/magazine/split-jurors.html) in place of the original 5 words indexed in the test.  

In my version, I use the `"language"` facet to restrict the query to just those divs that are English:

```xquery
declare
    %test:assertEquals(1)
function facet:query-no-default-index-but-facet() {
    let $result := doc("/db/lucenetest/multi-lang.xml")//div[ft:query(., (), map { "facets": map { "language": "en" } } )]
    return
        ft:facets($result, "language")?en
};
```

However, this version of the function fails the test, returning 0 hits instead of the expected 1 hit:

```xml
<testcase name="query-no-default-index-but-facet" class="facet:query-no-default-index-but-facet">
    <failure
        message="assertEquals failed: wrong number of items returned by function. Expected: 1. Got: 0"
        type="failure-error-code-1">1</failure>
    <output/>
</testcase>
```

Here is a standalone xqsuite with this function: [facets-trimmed.xql.zip](https://github.com/eXist-db/exist/files/4078712/facets-trimmed.xql.zip). It also includes a test that demonstrates the maxClauseCount error.

**Context (please always complete the following information):**
 - OS: macOS 10.15.2
 - eXist-db version: 5.2.0-SNAPSHOT (running @wolfgangmm's PR https://github.com/eXist-db/exist/pull/3142 since it contains an important fix to a bug affecting facets & field)
 - Java Version: Zulu 8.42.0.23-CA-macosx (build 1.8.0_232-b18)

**Additional context**
- How is eXist-db installed? DMG
- Any custom changes in e.g. `conf.xml`? None

**Comment by wolfgangmm** [comment]
Facets are tightly connected to lucene indexes. Passing `()` for the query string will just create a **catch-all** Lucene query. But with ` index="no"` there won't be any index to query and therefore the result is empty.

You should be able to query with `field:*` instead of `()` though, which is what I do in  most cases. In addition to `leading-wildcard`, you would also need to set `filter-rewrite` to "yes" to avoid the max-clause-count error. For example:

```xquery
declare namespace tei="http://www.tei-c.org/ns/1.0";

collection("/db/apps/kb-data")//tei:text[ft:query(., "file:*", map {
    "leading-wildcard": "yes",
    "filter-rewrite": "yes"
})]
```

**Comment by joewiz** [comment]
@wolfgangmm Ok, I see that the "filter-rewrite": "yes" avoids the max-clause-count error. I think this will work. Thank you!

This workaround strikes me as a bit unfortunate, since we really don't want to expose eXist to leading wildcards from user queries (i.e., every developer using this workaround will now need to sanitize user queries instead of relying on Lucene to raise the error)... What I'm suggesting is that as long as this wildcard approach is a kludge, do you think there would be some way to ensure that nodes with index=no, facet/field-only indexes, can respond respond to catch-all queries? For example, in the case of index=no indexes, could we supply some minimal dummy value (whitespace or nonsense word fed into the stopword list), so that catch-all queries could still catch these nodes? Otherwise, making use of the index="no" feature means you cannot use the catch-all feature, without introducing new complexity into the queries. Just a suggestion - adding a little more complexity into the core code to reduce the complexity of XQuery code?

**Comment by wolfgangmm** [comment]
@joewiz the options do not apply globally, they are limited to this particular call of `ft:query`. I thus can't see any risk as the wildcard is used for a single, fixed query string without any user interaction.  For user-facing queries you can use different options.

The problem is that you need to know the data set and the created indexes to understand which field can be used for a catch-all query. Only the developer is able  to tell.

**Comment by joewiz** [comment]
@wolfgangmm I see, yes, I can control the use of wildcard-enabled searches. Thanks again!

**Comment by jeanpaulrehr** [comment]
Coming back to this issue with a variation.  I’m creating facets on a self-closing element `<filiation corresp="#foo #bar"/>` using the following index. Being self closing, I assume this has the same effect on indexing as `index="no"`.

```
<text qname="tei:filiation">
     <facet dimension="textID" expression="./replace(@corresp,'#','') => tokenize(’ ')"/>
</text>
```

Monex tells me the facets `foo` and `bar` are there. But when I query the facet like so:

let $fils := $data//tei:filiation[ft:query(.,())]
return
    ft:facets($fils, "textID")

...I get an empty map. 

There are no other fields or facets on this element, but I tried @wolfgangmm 's suggestion above:

```
$data//tei:filiation[ft:query(., "field:*", map {
    "leading-wildcard": "yes",
    "filter-rewrite": "yes"
})]
```

But it's the same result.

I didn't see anything indicative in the Monex code that does it differently than the above? So how do I otherwise get facets from this self-closing element?

**Comment by joewiz** [comment]
@jeanpaulrehr I'm afraid your report is completely unrelated to this issue, because the issue here is about querying fields, not retrieving facets. The `leading-wildcard` workaround also only affects field queries. Thus, I'd encourage you to open a new issue. It shouldn't be hard to supply a reproducible test in the form of an XQSuite. For comparison/inspiration, see https://github.com/eXist-db/exist/blob/develop/extensions/indexes/lucene/src/test/xquery/lucene/facets.xql.
