### ISSUE TITLE
Exception override in string-join()

### ISSUE THREAD

**Issue by ptrckb** [eXist-db/exist#324]
If the evaluation of the parameters of `string-join()` triggers an error, the error gets overriden and is reported instead as a dynamic type mismatch.

In the following test-case `err:XPTY0004` is returned instead of `error`.

Tested with version 2.2RC2 and 2.1.

```xquery
xquery version "3.0";

declare function local:x() as xs:string { error(xs:QName('error')), 'x' };
    
try {
   string-join(( 'a', local:x() ))
} catch * {
   $err:code
}
```

**Comment by gmella** [comment]
:+1: 
Hi,
  This issue prevent the right error catching and report in our user interface. I suppose that improvment on this topic could save time on error debugging for many project.
I hope that this reminder may help to get the right level of priority :) .

Best wish and happy new year to the existdb community! Many thanks to the contributors of this very nice tool.
--
Guillaume

**Comment by gmella** [comment]
Hi,

  I just test on the daily distribution with version 
[eXist Version : 3.0.RC2] 
[eXist Build : 20160305] 
[Git commmit : develop-e0d6078]

but the issue is still present :(

Should we work arround this and avoid such kind of nested call ? Is there any other smarter way to get the first error ?

Best regards,
--
Guillaume

**Comment by dizzzz** [comment]
your query cannot be executed, there are syntax errors. That does not help accellerating  a fix...

```xquery
declare function local:x() as xs:string { 
     error(xs:QName('error')), 'x' 
};

try {
   string-join( 'a', local:x() )
} catch * {
   $err:code
}
```

**Comment by gmella** [comment]
Thank yo udizz for having a look on this.
Ok, the first given test-code had a bad xquery declaration. 
Next bunch of code seems valid:
```
xquery version "3.0";

declare function local:x($throw-error as xs:boolean) as xs:string { 
    let $gen-error := if($throw-error) then error(xs:QName('error')) else () 
    return 'x' 
};

for $i in (false(),true())
return
    try {
       string-join( ('a','b'), local:x($i) )  
    } catch * {
       $err:code
    }   
```

It returns (axb,err:XPTY0004) in exide instead of (axb,error).

Sorry, I don't see the second syntax error.

Regards,

**Comment by gmella** [comment]
Hi,

I just tried with the nignly build provided by Adam. The issue is still present :(
I also modified a little the snippet code to remove an 'unused variable' warning inside exide. This code seems clean ? 
May I try some other test to help fixing this ?
Regards,
--
Guillaume
[eXist Version : 3.0.RC2] 
[eXist Build : 20160509] 
[eXist Home : unknown] 
[Git commmit : develop-faded87] 
[Operating System : Linux 3.16.0-4-amd64 amd64]
