### ISSUE TITLE
[BUG] "variable is not set" error with mutual imported modules

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3449]
**Describe the bug**

When two library modules import each other, unexpected errors are raised by global variable declarations when eXist evaluates the 2nd module. 

**Expected behavior**

When eXIst compiles a library module that has mutual imports with another library module, eXist should not raise erroneous errors about undefined variables.

**To Reproduce**

Create `/db/test` and store the following two modules:

**/db/test/test1.xqm**

```xquery
xquery version "3.1";

module namespace test1 = "test1";

import module namespace test2 = "test2" at "test2.xqm";

declare variable $test1:a := "a";
```

**/db/test/test2.xqm**

```xquery
xquery version "3.1";

module namespace test2 = "test2";

import module namespace test1 = "test1" at "test1.xqm";

declare variable $test2:x := "x";

declare variable $test2:y := $test2:x || "y";
```

After storing these two queries, open test2.xqm and click Submit in Java admin client or Eval in eXide. The following error is raised:

```
org.xmldb.api.base.XMLDBException: err:XPDY0002 variable '$test2:x' is not set. [at line 9, column 31, source: xquery version "3.1";

module namespace test2 = "test2";

import module namespace test1 = "test1" at "test1.xqm";

declare variable $test2:x := "x";

declare variable $test2:y := $test2:x || "y";]
	at org.exist.xmldb.RemoteXPathQueryService.throwException(RemoteXPathQueryService.java:164)
	at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:108)
	at org.exist.xmldb.RemoteXPathQueryService.query(RemoteXPathQueryService.java:78)
	at org.exist.xmldb.RemoteXPathQueryService.execute(RemoteXPathQueryService.java:326)
	at org.exist.client.QueryDialog$QueryRunnable.run(QueryDialog.java:587)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.exist.xquery.XPathException: exerr:ERROR err:XPDY0002 variable '$test2:x' is not set. [at line 9, column 31, source: xquery version "3.1";

module namespace test2 = "test2";

import module namespace test1 = "test1" at "test1.xqm";

declare variable $test2:x := "x";

declare variable $test2:y := $test2:x || "y";] [at line 9, column 31]
	at org.exist.xmldb.RemoteXPathQueryService.throwException(RemoteXPathQueryService.java:163)
	... 5 more
```

Of course, library modules aren't meant to be directly evaluated, but IDEs like eXide do compile library modules to report static errors (and Java admin client happily accepts submission of library modules), so this is a valid use case. In these cases, eXist should not raise this error.

Neither BaseX nor Saxon raise such errors. They both happily validate test2.xqm.

**Context (please always complete the following information):**
 - OS: macOS 10.15.5
 - eXist-db version: 5.2.0, 5.3.0-SNAPSHOT
 - Java Version: JDK 1.8.0_252 (Zulu 8.46.0.19-CA-macosx) (build 1.8.0_252-b14)

**Additional context**
- How is eXist-db installed? 5.2.0 via DMG installer, 5.3.0-SNAPSHOT built from source 
- Any custom changes in e.g. `conf.xml`? None.

**Comment by adamretter** [comment]
@joewiz I would be very surprised if circular imports worked full stop due to eXist-db's eager evaluation nature and how it loads modules.

**Comment by adamretter** [comment]
This was previously fixed by myself on March 14th 2022, in commit: 8c7ff9d.

This now correctly raises the error: `EXXQDY0005 No function call details were provided when trying to execute a Library Module`.

**Comment by joewiz** [comment]
@adamretter Thank you for this information. I have a couple of questions:

1. Could you explain why an eXist should raise an error at all in this circumstance? As noted in the issue:

> Neither BaseX nor Saxon raise such errors. They both happily validate test2.xqm.

2. I couldn’t find the error code you mentioned, `EXXQDY0005`, in the eXist code base. The commit you referenced does contain a reference to an error message with similar wording though, `XPST0017`. Is that what you meant? The error message is defined in the spec (https://www.w3.org/TR/xpath-30/#ERRXPST0017) as:

> It is a [static error](https://www.w3.org/TR/xpath-30/#dt-static-error) if the [expanded QName](https://www.w3.org/TR/xpath-30/#dt-expanded-qname) and number of arguments in a static function call do not match the name and arity of a [function signature](https://www.w3.org/TR/xpath-30/#dt-known-func-signatures) in the [static context](https://www.w3.org/TR/xpath-30/#dt-static-context).

I am not quite sure why the condition described in my test case satisfies this condition or the one in your comment, “No function call details were provided…” But that gets back to the first question.

**Comment by adamretter** [comment]
> Could you explain why an eXist should raise an error at all in this circumstance? As noted in the issue:

The XQuery 3.1 specification states[^1]: `A library module cannot be evaluated directly; instead, it provides function and variable declarations that can be imported into other modules.`.

When you *"click Submit in Java admin client or Eval in eXide"* @joewiz  that is exactly what you are asking eXist-db to attempt to do!

@joewiz The XQuery specification however does not state whether an error should be raised or not, and if so what error code it should have. Therefore the behaviour here is allowed to be *"implementation defined"*.

> Neither BaseX nor Saxon raise such errors

Each implementation takes a different approach to evaluation. It is completely reasonable as far as I interpret the XQuery Specification for an implementation to return an error here. The alternative presumably would be to return an Empty Sequence as the result, however that would not be a representation of the truth as nothing had been evaluated to generate said Empty Sequence.

> I couldn’t find the error code you mentioned, EXXQDY0005, in the eXist code base. The commit you referenced does contain a reference to an error message with similar wording though, XPST0017. 

It looks like the error code was updated from `XPST0017` to the more appropriate `EXXQDY0005` since that commit. You can find it here: https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/xquery/XQuery.java#L423, here: https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/xquery/XQuery.java#L425, and here: 

> I am not quite sure why the condition described in my test case satisfies this condition or the one in your comment, “No function call details were provided…”

This is the first check that eXist-db does when trying to evaluate a Library Module as though it were a Main Module. i.e. You have a Library Module, but you are not executing a Main Module which would call a function in it (or calling a variable in it).

[^1]: https://www.w3.org/TR/xquery-31/#id-query-prolog

**Comment by joewiz** [comment]
Thank you for explaining that the solution here falls into the category of implementation defined—the new error is certainly an improvement over the old one—and pointing me to the current error code. I agree that this closes the issue.
