### ISSUE TITLE
Empty new lines be lefted as query result

### ISSUE THREAD

**Issue by HagayRatzabi** [eXist-db/exist#3944]
### What is the problem

After running this query(below):
```
xquery version "3.1";

declare function local:getSomething() as node(){
    <res>
        {
    for $t in collection('/db/LawRepoWiki/akn/il/act')
        return 
            <A>
                <B>{string($t//*[local-name()='body']/*[local-name()='title'])}</B>
            </A>
    }
    </res>
};

file:serialize(local:getSomething(),"test.txt",()) 
```
on this xml file (preview of partial file, text in hebrew - not important):
```
<act>
    <body period="#tmpg_1">
      <title eId="title">
        <content>
          <p> תקנות רישום שמות עסק, 1935</p>
        </content>
      </title>
    </body>
</act>
```
I get thie result:
```
 <res>
    <A>
        <B>
        
          תקנות רישום שמות עסק, 1935
        
      </B>
    </A>
    </res>
```

### What did you expect
 I don't want these empty lines, 
 I want it to look like this:
```
<res>
    <A>
        <B>        
          תקנות רישום שמות עסק, 1935
      </B>
    </A>
</res>
```

Please always add the following information
- eXist-db version 5.2
- Java version 1.8.0_171
- Operating system WIN 10
- 64 bit
- How is eXist-db installed? - JAR installer.
-  Running the query via eXide
- Any custom changes in e.g. conf.xml - no

**Comment by HagayRatzabi** [comment]
It related to eXide - how I move this issue to the suitable(eXide) project?

**Comment by joewiz** [comment]
Your question is actually not eXide-specific; it's a plain XQuery question. The "extra" whitespace you're seeing in the results are there in your source document. This is because your query applies the `string()` function to the `<title>` element. This element's string value starts with a span of whitespace including two newlines, and ends with a similar span including two newlines. If you want to collapse this whitespace, change `string()` to `normalize-space()`. That would produce:

```xml
<res>
    <A>
        <B>תקנות רישום שמות עסק, 1935</B>
    </A>
</res>
```

There is no serialization parameter that could further indent the child text node of the `<B>` element onto its own line. To achieve this you would need to manually construct this whitespace in your query.

Does this information solve your question? If so, please close it. If not, please let us know the remaining issues.

**Comment by HagayRatzabi** [comment]
Works!

Thanks friend, sorry for interruption and lack of knowledge...

**Comment by joewiz** [comment]
@HagayRatzabi Great! No worries - whitespace is definitely one of the trickier aspects of XQuery.
