### ISSUE TITLE
[BUG] 5.3.0 Dashboard broken

### ISSUE THREAD

**Issue by ahenket** [eXist-db/exist#3957]
**Describe the bug**
macOS 11.4, dmg version, eXist-db 5.3.0 release version, fresh database.

On a fresh database, the dashboard goes into http 404 after login on page /exist/apps/dashboard/admin#

**Expected behavior**
Going to the dashboard

**To Reproduce**
Install eXist-db, open Dashboard, login

**Screenshots**
![image](https://user-images.githubusercontent.com/5390573/123641025-13f14a00-d822-11eb-8ee8-473c747116bb.png)

**Context (please always complete the following information):**
 - OS: macOS 11.4
 - eXist-db version: 5.3.0
 - Java Version 15

**Additional context**
- dmg version, running on port 8877

**Comment by windauer** [comment]
This is very likely due to your browser caching some old JavaScript. For me closing and reopening my browser was sufficient to successfully load the package manager of the Dashboard with Firefox, Chrome and Safari. Please check and close the ticket if it works for you.

**Comment by ahenket** [comment]
No I think this is it. In Dashboard 2.0.6, you were rerouted from the first login to the second login window. In version 2.0.8 you are not rerouted anywhere.

I have never understood why one login routed into the other, but at least it worked. I've also never understood why the first login window (which is still present, doesn't support focus nor hitting return.

I put it to the test and resting these exact lines, restores 5.3.0 release

![image](https://user-images.githubusercontent.com/5390573/123643042-48660580-d824-11eb-8236-2c7e635b1020.png)

**Comment by windauer** [comment]
I can only repeat myself, had the exact same issue and clearing my Chrome caches fixed it for me (shift reload did not!). Since then it works as intended on Chrome, Safari and Firefox. I only experienced the issue in Chrome btw. The changes in Dashboard 2.0.8 were intended by @JoernT to cleanup the messy [login](https://github.com/eXist-db/dashboard/commit/0da69dc927baf73af9250459b25a3b43561dc69c ).  if the issue still persist with a cleaned up  browser please let us know, I just checked again with a fresh 5.3.0 it here it simply works now with all browser.  I do understand thats its frustrating when it seems like its broken on the first view after an upgrade .. But I guess thats a ticket for the  [Dashboard repo](https://github.com/eXist-db/dashboard) and not eXist-db repo.

**Comment by JoernT** [comment]
@ahenket the new dashboard does accept enter for login dialog now.

**Comment by wolfgangmm** [comment]
I confirm @windauer's observations: clearing chrome's browser cache fixed the issue for me - as well as using firefox, which I do not fire up as often as chrome.

**Comment by ahenket** [comment]
Clearing the Safari cache in the develop menu worked for me too. That closes this ticket as non-issue.

@JoernT: Confirm that hitting Enter indeed works. Thanks. Hitting tab key after onOpen() brings you into the user field, but autofocus would have been more ideal.

**Comment by JoernT** [comment]
Alexander,

just because you mentioned it - there is autofocus on the user field. If it
does not work for you that'll be another issue.

Joern
