### ISSUE TITLE
[BUG] xmldiff:compare catches an exception 

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#4048]
**Describe the bug**
in a number of cases `xmldiff:compare#2` returns `exerr:ERROR An exception occurred while serializing node for comparison: Caught exception during comparison` 

**Expected behavior**
I expect `false()` to be returned, or `true()`, see tests below.

**To Reproduce**

```xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare %test:assertTrue function t:test-with-two-identical-nodes-succeeds() {
    let $a := (<foo/>)
    let $b := (<foo/>)
    return
        xmldiff:compare($a, $b)
};
declare %test:assertFalse function t:test-with-two-different-nodes-succeeds() {
    let $a := (<foo bar=""/>)
    let $b := (<foo/>)
    return
        xmldiff:compare($a, $b)
};
declare %test:assertTrue function t:test-with-two-identical-node-sequences-fails() {
    let $a := (<foo/>,<bar/>)
    let $b := (<foo/>,<bar/>)
    return
        xmldiff:compare($a, $b)
};
declare %test:assertFalse function t:test-with-two-different-node-sequences-fails() {
    let $a := (<foo/>,<bar/>)
    let $b := (<foo/>,<meh/>)
    return
        xmldiff:compare($a, $b)
};
declare %test:assertFalse function t:test-with-sequences-of-unequal-length-fails() {
    let $a := (<foo/>,<bar/>)
    let $b := (<foo/>)
    return
        xmldiff:compare($a, $b)
};
declare %test:assertFalse function t:test-with-sequence-of-two-and-empty-sequence-succeeds() {
    let $a := (<foo/>,<bar/>)
    let $b := ()
    return
        xmldiff:compare($a, $b)
};
```
I think the reason why the pattern is the way it is (with the last test succeeding), is that there is a false thrown after the first node comparison. I think the function cannot compare more than one node, although the signature says it does: `xmldiff:compare($node-set-1 as node()*, $node-set-2 as node()*)`

exist 5.3.0, windows 10, amazon corretto 1.8.282

**Comment by adamretter** [comment]
Okay I can see the issue...

1. The function signature does allow more than one node at a time to `$node-set-1` and/or `$node-set2`
2. If there is more than one node to either of the args, then the function serializes each node in-turn into a string, and concatenates them together.

The error you are seeing is caused by for example:
```
xmldiff:compare((<a/><b/>), (<a/>))
```

In this instance the String `"<a/><b/>"` when parsed as XML is not a well-formed XML document, which is why you are seeing errors.

The approach is deeply flawed and needs to be fixed. I think we may have already addressed this in FusionDB - let me take a look and see if I can make some improvements based on that to eXist-db.
