### ISSUE TITLE
[BUG] eXist-db 5.4.0 Release link to release notes empty

### ISSUE THREAD

**Issue by bwbohl** [eXist-db/exist#4210]
**Describe the bug**
The Release Notes linked from the 5.4.0 Release result in an empty page only containing the warning:
"Either the feed is empty or you are not allowed to view the entries."

**Expected behavior**
Content of the Release notes

**To Reproduce**
Visit https://github.com/eXist-db/exist/releases/tag/eXist-5.4.0 click the link at "Release Notes" being
https://exist-db.org/exist/apps/wiki/blogs/eXist/eXistdb540

**Comment by line-o** [comment]
This is also true for the other recent releases 4.9.0 and 4.10.0.

**Comment by PieterLamers** [comment]
I have a few suggestions (or stated otherwise: I would like to know if the following changes have made it into this release):
- support for map:merge#2
- change default merge behavior to comply with the spec (or is that change reserved for 6.0.0?)
- change of generate-id#1 to have unique in-memory IDs
- latest log4j vulnerability fix (seeing 2.15 > 2.17.1 change in develop, don't know whether this means that 5.4.0 is on 2.15)

I'd prioritize documenting the eXist 5-branch over eXist-4 if the changelog is too time consuming.

**Comment by line-o** [comment]
1. yes
2. no (will be released in 7.0.0, I believe)
3. no idea
4. no

**Comment by PieterLamers** [comment]
Thanks for your feedback @line-o . I just learned that https://github.com/eXist-db/exist/pull/4167 is also part of the release.

**Comment by adamretter** [comment]
@bwbohl @PieterLamers The release process is still in process. The first stage was to produce the binaries, we haven't announced the releases yet. The release notes will follow soon, your patience is appreciated.

**Comment by bwbohl** [comment]
didn't mean to push (just was curious as GitHub announced it in my notifications ;-)
