### ISSUE TITLE
[BUG] wrong script tag content when serializing xhtml

### ISSUE THREAD

**Issue by ccheraa** [eXist-db/exist#4598]
**Describe the bug**
When serializing an `xhtml` node to string, any XML entities in the `text` node in `script` tags will be escaped.

```html
<script>1>2</script>
```

When parsed, then serialized, it becomes:

```xhtml
<script>1&amp;2</script>
```

**Expected behavior**
Any XML entities in JavaScript code inside an `xhtml:script` tag should not be escaped.

**To Reproduce**

```Xquery
xquery version "3.1";

module namespace t="http://exist-db.org/xquery/test";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare variable $t:html-input := "<!DOCTYPE html>
<html>
  <head>
    <title>X</title>
  </head>
  <body>
    <script>1>2</script>
  </body>
</html>";

declare
    %test:assertTrue
function t:test() {
    let $html-node := util:parse-html($t:html-input)
    let $html-output := serialize($html-node)
    return contains($html-output, "1>2")
    (: contains($html-output, "1&amp;gt;2") returns true :)
};
```

**Context (please always complete the following information):**
 - OS: macOS 13.0.0 / Ubuntu 20.04.1
 - eXist-db version: [6.1.0-SNAPSHOT](https://github.com/evolvedbinary/exist/tree/feature/jetty-11)
 - Java Version openjdk 17.0.4 2022-07-19

**Additional context**
- How is eXist-db installed? prebuilt archive on https://static.evolvedbinary.com/cadit/exist-distribution-6.1.0-SNAPSHOT-unix.tar.bz2
- Any custom changes in e.g. `conf.xml`? No

**Comment by adamretter** [comment]
Hi @ccheraa by default `fn:serialize` will assume that you are serializing XML and produce a string representation of XML.

If you wanted to instead serialize to XHTML, you need to provide a `method` parameter that informs it to do so. For example:

```xquery
serialize($html-node, map { "method": "xhtml" })
```

However, as XHTML must be valid XML, that will still produce output where the `1>2` is encoded to `1&amp;2`. This is because XML requires the `>` to be encoded for the document to be well-formed.

Instead, you may want to just produce HTML output, which will then not encode the `>` as it is not XML: 
```xquery
serialize($html-node, map { "method": "html" })
```
