### ISSUE TITLE
[BUG] System configuration leads to empty jetty-http.xml and jetty-ssl.xml

### ISSUE THREAD

**Issue by ahenket** [eXist-db/exist#4729]
**Describe the bug**
The macOS version of eXist-db comes with a minimal UI that allow access to System Configuration. This, among other things lets you change the ports that eXist-db runs on. Our preferred ports are 8877 for http and 8843 for https.

However setting them using the eXist-db system bar feature System Configuration is unreliable.

**Expected behavior**
When you set the new ports you expect those to actually be applied

**To Reproduce**

- Copy eXist-db.app to Applications folder and start it up from there (no other changes)
  - eXist-db.app will present you the system configuration screen
- Change the Jetty Ports and Save. http = 8877 and ssl = 8843
  - eXist-db will now continue to load. In the exist.log you will see it loads using the default ports and ignore what you Saved
- While the db is running, choose System Configuration from the eXist-db menubar icon
- Change the Jetty Ports and Save again. http = 8877 and ssl = 8843
  - As soon you hit Save you will see that the once 1kb jetty-http.xml and jetty-ssl.xml will be turned into 0kb files

**Screenshots**

**Context (please always complete the following information)**
 - Build: [eXist-6.2.0]
 - Java: [java version "15.0.2" 2021-01-19]
 - OS: [Mac OS X 13.1 Ventura]

**Additional context**
- Installed from dmg

**Comment by ahenket** [comment]
Side note that might be related: opening the exist.log from this same system bar utility also fails to happen since 6.0.1/6.2.0. A much beloved feature as the log is deep inside the .app.

**Comment by bansp** [comment]
I'd like to confirm this for: 

[eXist Version : 6.2.0] 
[eXist Build : 2023-02-04T22:42:29Z] 
[Git commit : c8fa4958b6d4a50bd0cba7f3e76a150226414187] 
[Git commit timestamp : 20230204223916] 
[Operating System : Linux 4.15.0-206-generic amd64]
java version "1.8.0_111"  

Installed from .jar


This is the state after having adjusted the ports in the configuration window that shows up at first run (and without that action having consequences for jetty, but you see the consequences in the renamed files:

![image](https://user-images.githubusercontent.com/312137/227071876-b4bb54bd-f677-4106-bc1d-72f958b013a9.png)

Then I repeated the action that @ahenket mentions: invoked the configuration window, modified the ports, saved, agreed to a restart, and noticed an error at the moment that jetty http configuration loaded: premature end of file. On the disk, it looked as follows:

![image](https://user-images.githubusercontent.com/312137/227072184-b745dfb3-9629-401b-948e-f7a83fdebc90.png)

```
:~/eXist-db/etc/jetty$ diff jetty-http.xml.orig.20230323015522 jetty-http.xml.orig.20230323013147 
1c1,8
< <?xml version="1.0" encoding="UTF-8"?><!-- ============================================================= --><!-- Configure the Jetty Server instance with an ID "Server"       --><!-- by adding a HTTP connector.                                   --><!-- This configuration must be used in conjunction with jetty.xml --><!-- ============================================================= --><!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
---
> <?xml version="1.0"?>
> <!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_9_3.dtd">
> 
> <!-- ============================================================= -->
> <!-- Configure the Jetty Server instance with an ID "Server"       -->
> <!-- by adding a HTTP connector.                                   -->
> <!-- This configuration must be used in conjunction with jetty.xml -->
> <!-- ============================================================= -->
17c24
<         <Arg name="server"><Ref refid="Server"/></Arg>
---
>         <Arg name="server"><Ref refid="Server" /></Arg>
24c31
<                 <Arg name="config"><Ref refid="httpConfig"/></Arg>
---
>                 <Arg name="config"><Ref refid="httpConfig" /></Arg>
42c49
< </Configure>
\ No newline at end of file
---
> </Configure>
```

(I also failed to open the log from the system bar.)

HTH and thanks!

**Comment by bansp** [comment]
Just letting you guys know that the bug is still there, in 6.3.0.
The first run results in the same effect as in my first screenshot above (down to the modifications in the file size):

~/eXist-db/etc/jetty$ ll jetty-http.xml* jetty-ssl.xml*
-rw-rw-r-- 1 piotr piotr    0 Nov 21 16:26 jetty-http.xml
-rw-rw-r-- 1 piotr piotr 3214 Nov 21 16:20 jetty-http.xml.orig.20241121162046
-rw-rw-r-- 1 piotr piotr 3216 Nov 21 16:26 jetty-http.xml.orig.20241121162610
-rw-rw-r-- 1 piotr piotr    0 Nov 21 16:26 jetty-ssl.xml
-rw-rw-r-- 1 piotr piotr 3652 Nov 21 16:20 jetty-ssl.xml.orig.20241121162044
-rw-rw-r-- 1 piotr piotr 3632 Nov 21 16:26 jetty-ssl.xml.orig.20241121162609

(the -ssl loses 20 bytes on the first run, then goes to 0; the -http gets 2 bytes on the first run, then gets to 0)

Interaction with the system bar is also impossible, on the second run, as above. 

**Context**
Running with Java 17.0.11 [Ubuntu (OpenJDK 64-Bit Server VM) in /usr/lib/jvm/java-17-openjdk-amd64]
[eXist Version : 6.3.0] 
[eXist Build : 2024-10-26T10:10:00Z] 
[Git commit : f040b832284f81f095e89c06fe9e30a78654dd9b] 
[Git commit timestamp : 20241026113332] 
[Operating System : Linux 6.5.0-44-generic amd64] 
[jetty Version: 9.4.54.v20240208] 

Regression? One way or another, I suggest that the ticket should get reopened.
