### ISSUE TITLE
[BUG] inline element in the collection.xconf is not applied correctly 

### ISSUE THREAD

**Issue by marmoure** [eXist-db/exist#4789]
I am facing a case whereby the `<inline>` element in `collection.xconf` is not being ignored correctly. This results in unexpected results from the search.

# How to reproduce the issue
from a clean exist instance 
* Download this Lucene Analyzer  to your eXist-db `lib` folder: https://github.com/evolvedbinary/PLMultiAnalyzer/releases/download/alpha-v2/PLMultiAnalyzer-1.0.0-SNAPSHOT.jar
* Add the following as a child to the `<dependencies>` element in the file`etc/startup.xml` within your eXist-db folder.
```xml
<dependency>
    <groupId>com.evolvedbinary.lucene.analyzer</groupId>
    <artifactId>PLMultiAnalyzer</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>PLMultiAnalyzer-1.0.0-SNAPSHOT.jar</relativePath>
</dependency>
  ```

Then startup eXist-db, and run this script:
```xquery
xquery version "3.1";

import module namespace kwic = "http://exist-db.org/xquery/kwic";

(: setup :)
let $data := 
    <div>
        <head>150. Editorial Note</head>
        <p>On March 14, the Operations Coordinating Board approved a Progress Report
          on <gloss target="#t_NSC1">NSC</gloss> 5612/1. (Department of State,
          S/P–<gloss target="#t_NSC1">NSC</gloss> Files: Lot 62 D 1, <gloss target="#t_NSC1">NSC</gloss> 5612 Series) <gloss target="#t_NSC1">NSC</gloss> 5612/1 is printed as <ref target="#d119">Document119</ref>.
        </p>
        <p>At the <gloss target="#t_NSC1">NSC</gloss> meeting on May 2, the Council,
          according to <gloss target="#t_NSC1">NSC</gloss> Action No. 1711, "noted
          and discussed" the Progress Report. (Department of State, S/S–<gloss target="#t_NSC1">NSC</gloss> Files (Miscellaneous) Files: Lot 66 D
          95) The <gloss target="#t_NSC1">NSC</gloss> did not discuss the
          substance of the Progress Report. (Memorandum of discussion by <persName corresp="#p_GSE1">Gleason</persName>, May 2; Eisenhower Library,
          S/S–NSC Whitman File, <gloss target="#t_NSC1">NSC</gloss> Records)
        </p>
    </div>
let $xconf := 
    <collection xmlns="http://exist-db.org/collection-config/1.0">
      <index xmlns:wiki="http://exist-db.org/xquery/wiki" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:atom="http://www.w3.org/2005/Atom">
        <!-- Lucene index is configured below -->
        <lucene>
          <analyzer class="com.evolvedbinary.lucene.analyzer.OhAnalyzer">
            <param name="punctuationDictionary" type="char[]">
              <value>-</value>
              <value>–</value>
              <value>—</value>
              <value>.</value>
              <value>,</value>
              <value>;</value>
              <value>:</value>
              <value>'</value>
              <value>‘</value>
              <value>’</value>
              <value>“</value>
              <value>”</value>
              <value>(</value>
              <value>)</value>
              <value>[</value>
              <value>]</value>
              <value>/</value>
            </param>
            <param name="minimumTermLength" type="int" value="2"/>
          </analyzer>
          <text qname="div">
            <inline qname="gloss"/>
          </text>
        </lucene>
      </index>
    </collection>
let $xconf-col := xmldb:create-collection("/db/system/config/db", "temp")
let $store-xconf := xmldb:store($xconf-col, "collection.xconf", $xconf)
let $data-col := xmldb:create-collection("/db", "temp")
let $store-data := xmldb:store($data-col, "test.xml", $data)

(: the heart of the test :)
let $q := "`S\/S–NSC`"
let $doc := doc($store-data)
let $hits := $doc//div[ft:query(., "`S\/S–NSC`")]

for $hit in $hits
    return kwic:expand($hit)//exist:match
```

If you have setup and run the above XQuery correctly, you will see the following (incorrect) results:
```xml
<exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–</exist:match>
<exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–NSC</exist:match>
```

This is not the behaviour we are expecting. Instead we expect to see:
```xml
<exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–NSC</exist:match>
<exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–NSC</exist:match>
```

It looks like the `<gloss>` inline element is affecting the search even though it was added to the `collection.xconf`.

built from: ece817f244fd0a257e491ea210a9268171390f9c

**Comment by duncdrum** [comment]
what's the existdb version?

**Comment by marmoure** [comment]
we did some work regarding this to prove weather is this an issue or not
so we figured that the inline elements are being processed  correctly
and the text extraction is working fine
you can see the text being sent to the analyzer in here https://github.com/eXist-db/exist/blob/ece817f244fd0a257e491ea210a9268171390f9c/extensions/indexes/lucene/src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java#L1451
if you set a break point and look at the doc content

as for the wrong results posted in this issue it was due to a fault in exist match design

**Comment by line-o** [comment]
@marmoure what fault in exist match design?

**Comment by line-o** [comment]
@marmoure If there is a (new) issue in highlight matches, could you open an issue on that?

**Comment by marmoure** [comment]
@line-o in the example above we are expecting
```xml
<exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–NSC</exist:match>
```
but we are getting
```xml
<exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–</exist:match>
```
we are getting the correct match but when it comes to exist match to wrap it
it only wraps the text before the `inline` element as oppose to wrap the whole match 
`S/S–<gloss target="#t_NSC1">NSC</gloss>`
which might look like 
```xml
<exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–<gloss target="#t_NSC1">NSC</gloss></exist:match>
```
i m not sure if exist match is expected to extract the text

in this case it might look simple but let's assume there is more text inside that `<gloss>` inline element
should `exist:match` show the full `inline` node  like?
```xml
<exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–<gloss target="#t_NSC1">NSC more text</gloss></exist:match>
```

or should it extract the text and only show the matching bits?

**Comment by line-o** [comment]
@marmoure There is this issue open #4584 
If it's closely related you might want to add your test case there.

**Comment by marmoure** [comment]
thank you so much @line-o

**Comment by adamretter** [comment]
@marmoure So I have looked into this a bit and debugged the Lucene code. I believe that in terms of Indexing there is no problem with the `<inline>` element in the config, the correct text does seem to be passed to the Indexer (and furthermore the Analyzer). This is the text that I was able to intercept with the debugger that is passed to the Indexer and Analyzer:
```
150. Editorial Note On March 14, the Operations Coordinating Board approved a Progress Report
on NSC 5612/1. (Department of State,
S/P–NSC Files: Lot 62 D 1, NSC 5612 Series) NSC 5612/1 is printed as Document119 .
At the NSC meeting on May 2, the Council,
according to NSC Action No. 1711, "noted
and discussed" the Progress Report. (Department of State, S/S–NSC Files (Miscellaneous) Files: Lot 66 D
95) The NSC did not discuss the
substance of the Progress Report. (Memorandum of discussion by Gleason , May 2; Eisenhower Library,
S/S–NSC Whitman File, NSC Records)
```

Note that the `<inline qname="gloss"/>` index configuration option, has correctly made sure that no whitespace is introduced around the `S/S–NSC` terms.

----

Furthermore, I think that this is actually producing the correct results as far as the eXist-db KWIC (`exist:match`) feature is capable at this time. If you change `return kwic:expand($hit)//exist:match` to just `return kwic:expand($hit)` so that we can see where the `exist:match` elements are appearing, then we see the results:
```xml
<div>
    <head>150. Editorial Note</head>
    <p>On March 14, the Operations Coordinating Board approved a Progress Report
          on <gloss target="#t_NSC1">NSC</gloss> 5612/1. (Department of State,
          S/P–<gloss target="#t_NSC1">NSC</gloss> Files: Lot 62 D 1, <gloss target="#t_NSC1">NSC</gloss> 5612 Series) <gloss target="#t_NSC1">NSC</gloss> 5612/1 is printed as <ref target="#d119">Document119</ref>.
        </p>
    <p>At the <gloss target="#t_NSC1">NSC</gloss> meeting on May 2, the Council,
          according to <gloss target="#t_NSC1">NSC</gloss> Action No. 1711, "noted
          and discussed" the Progress Report. (Department of State, <exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–</exist:match>
        <gloss target="#t_NSC1">NSC</gloss> Files (Miscellaneous) Files: Lot 66 D
          95) The <gloss target="#t_NSC1">NSC</gloss> did not discuss the
          substance of the Progress Report. (Memorandum of discussion by <persName corresp="#p_GSE1">Gleason</persName>, May 2; Eisenhower Library,
          <exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–NSC</exist:match> Whitman File, <gloss target="#t_NSC1">NSC</gloss> Records)
        </p>
</div>
```

So to explain this, the problem you are seeing is **not** related to your Analyzer or any bug particularly. The output you are seeing is related to the current abilities/limitations of `exist:match` as managed by `NativeSerializer.java` in eXist-db (called via. `kwic.xql`, via.  `util:expand`).

That is to say that the current implementation of `exist:match` will not wrap around node boundaries and is not aware of the `<inline>` index configuration.

That is to say that at the moment the Serliazer where the `<inline>` concern is, currently produces this:
```xml
(Department of State, <exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–</exist:match><gloss target="#t_NSC1">NSC</gloss> Files
```

The Serializers current implementation of `<exist:match>` is not capable of putting the `<exist:match>` tags around node boundaries, which is why you do **not** get:
```xml
(Department of State, <exist:match xmlns:exist="http://exist.sourceforge.net/NS/exist">S/S–<gloss target="#t_NSC1">NSC</gloss></exist:match> Files
```

This could be improved in future but it is non-trivial, as there are potentially ["overlap"](https://en.wikipedia.org/wiki/Overlapping_markup) issues.

I think we should try and document this in the `inline` section of the Full-text Indexing documentation for eXist-db - https://www.exist-db.org/exist/apps/doc/lucene#inline

@marmoure I suspect that producing the output that you would like would be a fairly involved feature request instead...

**Comment by brihaye** [comment]
Hi,

Le 07/03/2023 13:13, Adam Retter a écrit :

> @marmoure [1] So I have looked into this a bit and debugged the Lucene
> code. I believe that in terms of Indexing there is no problem with the
> <inline> element in the config, the correct text does seem to be
> passed to the Indexer (and furthermore the Analyzer). This is the text
> that I was able to intercept with the debugger that is passed to the
> Indexer and Analyzer

Yes.

That's why I was asking the possibility to define a configurable match 
serializer years ago... One could imagine a way to serialize the XML 
structure around the indexed text... Myself, I've used this kind of 
feature to serialize arabic terms in... english.

So, yes, It's non trivial but it could be really useful...


Cheers,

p.b.

**Comment by brihaye** [comment]
FYI, here is the code :

https://git.savannah.nongnu.org/cgit/aramorph.git/tree/src/java/gpl/pierrick/brihaye/aramorph/lucene/ArabicGlosser.java

20 years ago, wow ! :-)


p.b.
