### ISSUE TITLE
WebDAV should be upgraded to Milton 1.8.1.4

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#718]
As per the discussion [here](http://milton-users.96038.n3.nabble.com/1-8-1-3-Jars-missing-from-maven-repo-td4025347.html), Milton 1.8.1.3 Jar files are no longer obtainable and are known to have bugs. Having attempted to replace with 1.8.1.4, this does seem to be a drop-in replacement.

@dizzzz Any complaints?

**Comment by adamretter** [comment]
Okay so it seems that 1.8.1.4 is under GPL v3.0. Whereas 1.8.1.3 is under Apache v2.0 :-(

**Comment by pboz** [comment]
http://www.wtfpl.net/wp-content/uploads/2012/12/wtfpl-strip.jpg

**Comment by adamretter** [comment]
@pboz :-)

**Comment by dizzzz** [comment]
I think (again) two routes are messed up
1) for the 1.8.x versions, the latest fixes are very minimal, updating JAR files does not solve real issues
2) for the 2.x version we have a licensing issue;

for (2) I have been in contact with the author, he is willing, but we did not settle a real agreement. It is by far no drop-in replacement hence I did not put any effort in it.

in addition: the past has shown that WebDAV is horribly supported by large vendors like MS en apple. unclear requirements, changing implementations (Finder, but also some linux inplementations) turned out a hard job to support. not really encouraging :-)
