### ISSUE TITLE
Add mailing list info to readme.MD

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#753]
From https://twitter.com/albertovski/status/624156766473973765:

> @joewiz @existdb Thanks. I didn’t find any reference to exist-open in the github page or website. Subscribing, thanks :-)

**Comment by dizzzz** [comment]
actually it is there: "If you're looking for help or discussion, visit the eXist community mailing lists or......"

**Comment by dizzzz** [comment]
maybe it is a virus scanner thing; i will continue to investigate but the error is..... vague

**Comment by joewiz** [comment]
You're right. I should've checked first. Sorry!

**Comment by dizzzz** [comment]
i'd vote to split the README.md a bit ; the text is rather long, so why not a DEVELOP.md containing most of the text, a README.md providing a limited introduction, link to the documentation and a link do DEVELOP.md  The current file scares me a bit off.... due to the size and the load of details in it.

**Comment by adamretter** [comment]
@dizzzz I think the README.md should stay as it is. It is aimed at developers (and it appears as the text on our GitHub page), it briefly points to the website etc for non-developer docs.
